import { Router } from "express";
import multer from "multer";
import { rateLimit } from "express-rate-limit";
import { z } from "zod";
import { authenticate } from "../../middleware/authenticate.js";
import { requireSchoolContext } from "../../middleware/requireSchoolContext.js";
import { requireClasspilotEntitlement } from "../../middleware/requireClasspilotEntitlement.js";
import { requireRole } from "../../middleware/requireRole.js";
import { readOneRosterZip } from "../../services/oneRosterCsv.js";
import { ROSTER_LIMITS, rosterError } from "../../services/rosterIntegrationModel.js";
import { applyRosterRun, disconnectRosterConnection, findRosterCandidates, getRosterRun, listRosterConnections, listRosterRuns, previewRosterRun, publicRosterRun, queueCleverRosterSync, saveRosterConnection, stageRosterPackage } from "../../services/rosterIntegrationStore.js";
import type { RosterPlan } from "../../services/rosterIntegrationPlanner.js";
import { assertRosterReviewPlan, rosterReviewPage } from "../../services/rosterIntegrationReview.js";

const router=Router();
router.use(authenticate,requireSchoolContext,requireClasspilotEntitlement,requireRole("admin","school_admin"));
const mutationLimit=rateLimit({windowMs:15*60_000,limit:100,standardHeaders:true,legacyHeaders:false});
const id=z.string().trim().min(1).max(256);
const mapping=z.object({organizationIds:z.array(id).min(1).max(100),people:z.record(id).optional(),classes:z.record(id).optional(),adoptPeople:z.array(id).max(10000).optional(),adoptClasses:z.array(id).max(10000).optional()}).strict();
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:ROSTER_LIMITS.compressedBytes,files:1,fields:0,parts:1}});
const scope=(req:any,res:any)=>({schoolId:String(res.locals.schoolId),userId:String(req.authUser.id)});
const parse=<T>(schema:z.ZodType<T>,value:unknown):T=>{const result=schema.safeParse(value);if(!result.success)throw rosterError("ROSTER_INPUT_INVALID",result.error.issues.map(issue=>`${issue.path.join(".")}: ${issue.message}`).slice(0,5).join(" "));return result.data;};
router.get("/",async(req,res,next)=>{try{return res.json({connections:await listRosterConnections(scope(req,res).schoolId)});}catch(error){next(error);}});
router.post("/",mutationLimit,async(req,res,next)=>{try{const body=parse(z.object({provider:z.enum(["oneroster","clever"]),name:z.string().trim().min(1).max(120),providerIdentity:id,token:z.string().trim().min(16).max(4096).optional()}).strict(),req.body);if(body.provider==="clever"&&!body.token)throw rosterError("CLEVER_TOKEN_REQUIRED","Provide the district data token.");return res.status(201).json({connection:await saveRosterConnection({...scope(req,res),...body})});}catch(error){next(error);}});
router.patch("/:id",mutationLimit,async(req,res,next)=>{try{const body=parse(z.object({expectedRevision:z.number().int().min(0),name:z.string().trim().min(1).max(120).optional(),token:z.string().trim().min(16).max(4096).optional(),automaticSync:z.boolean().optional(),status:z.enum(["active","paused"]).optional(),mapping:mapping.optional()}).strict(),req.body);return res.json({connection:await saveRosterConnection({...scope(req,res),id:String(req.params.id),...body})});}catch(error){next(error);}});
router.post("/:id/disconnect",mutationLimit,async(req,res,next)=>{try{const body=parse(z.object({expectedRevision:z.number().int().min(0)}).strict(),req.body);const {schoolId,userId}=scope(req,res);return res.json({connection:await disconnectRosterConnection(schoolId,String(req.params.id),userId,body.expectedRevision)});}catch(error){next(error);}});
router.post("/:id/upload",mutationLimit,(req,res,next)=>upload.single("file")(req,res,error=>{if(error)return next(rosterError("ROSTER_UPLOAD_INVALID","Upload one ZIP file no larger than 25 MiB."));next();}),async(req,res,next)=>{try{if(!req.file)throw rosterError("ROSTER_UPLOAD_REQUIRED","Select the OneRoster ZIP export.");const snapshot=await readOneRosterZip(req.file.buffer);const {schoolId,userId}=scope(req,res);return res.status(201).json({run:publicRosterRun(await stageRosterPackage(schoolId,String(req.params.id),snapshot,userId))});}catch(error){next(error);}});
router.post("/:id/sync",mutationLimit,async(req,res,next)=>{try{const {schoolId,userId}=scope(req,res);return res.status(202).json({run:publicRosterRun(await queueCleverRosterSync(schoolId,String(req.params.id),userId))});}catch(error){next(error);}});
router.get("/:id/runs",async(req,res,next)=>{try{return res.json({runs:await listRosterRuns(scope(req,res).schoolId,String(req.params.id))});}catch(error){next(error);}});
router.get("/runs/:id",async(req,res,next)=>{try{return res.json({run:publicRosterRun(await getRosterRun(scope(req,res).schoolId,String(req.params.id)))});}catch(error){next(error);}});
router.get("/runs/:id/rows",async(req,res,next)=>{try{const run=await getRosterRun(scope(req,res).schoolId,String(req.params.id));const plan=run.plan as RosterPlan|null;assertRosterReviewPlan(plan,run.planHash,String(req.query.planHash||""));const page=parse(z.coerce.number().int().min(0).max(1000000),req.query.page||0);const kind=String(req.query.kind||"all");const all=plan.steps.filter(step=>kind==="all"||step.kind===kind);return res.json({planHash:run.planHash,total:all.length,rows:all.slice(page*50,page*50+50).map(step=>({kind:step.kind,externalId:step.externalId,internalId:step.internalId,create:step.create,changes:step.data,studentCount:step.studentIds?.length,coTeacherCount:step.coTeacherIds?.length,ownedFields:step.ownedFields,name:step.review!.name,fieldChanges:step.review!.fields,membershipChanges:step.review!.members.length}))});}catch(error){next(error);}});
router.get("/runs/:id/review",async(req,res,next)=>{try{const run=await getRosterRun(scope(req,res).schoolId,String(req.params.id));return res.json(rosterReviewPage(run.plan as RosterPlan|null,run.planHash,String(req.query.planHash||""),Number(req.query.page||0)));}catch(error){next(error);}});
router.get("/:id/candidates",async(req,res,next)=>{try{const type=parse(z.enum(["teacher","student","class"]),req.query.type||"teacher");return res.json({candidates:await findRosterCandidates(scope(req,res).schoolId,String(req.params.id),type,String(req.query.q||""))});}catch(error){next(error);}});
router.post("/runs/:id/preview",mutationLimit,async(req,res,next)=>{try{const body=parse(z.object({mapping}).strict(),req.body);return res.json({run:publicRosterRun(await previewRosterRun(scope(req,res).schoolId,String(req.params.id),body.mapping))});}catch(error){next(error);}});
router.post("/runs/:id/apply",mutationLimit,async(req,res,next)=>{try{const body=parse(z.object({planHash:z.string().regex(/^[a-f0-9]{64}$/),approveHeld:z.boolean().optional()}).strict(),req.body);const {schoolId,userId}=scope(req,res);return res.json({run:publicRosterRun(await applyRosterRun(schoolId,String(req.params.id),body.planHash,userId,body.approveHeld===true))});}catch(error){next(error);}});
export default router;
