import sgMail from "@sendgrid/mail";

const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY || "";
const FROM_EMAIL = process.env.SENDGRID_FROM || "noreply@school-pilot.net";
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || "bzinkan@school-pilot.net";

if (SENDGRID_API_KEY) {
  sgMail.setApiKey(SENDGRID_API_KEY);
}

export async function sendEmail(options: {
  to: string;
  subject: string;
  text?: string;
  html?: string;
}): Promise<boolean> {
  if (!SENDGRID_API_KEY) {
    console.log(`[Email] Would send to ${options.to}: ${options.subject}`);
    return true;
  }

  try {
    await sgMail.send({
      to: options.to,
      from: FROM_EMAIL,
      subject: options.subject,
      text: options.text || "",
      html: options.html || "",
    });
    return true;
  } catch (error) {
    console.error("[Email] Send failed:", error);
    return false;
  }
}

export async function sendWelcomeEmail(to: string, schoolName: string, tempPassword: string): Promise<boolean> {
  return sendEmail({
    to,
    subject: `Welcome to SchoolPilot - ${schoolName}`,
    html: `
      <h2>Welcome to SchoolPilot!</h2>
      <p>Your school <strong>${schoolName}</strong> has been set up.</p>
      <p>Your temporary password is: <code>${tempPassword}</code></p>
      <p>Please log in and change your password immediately.</p>
      <p>Login at: ${process.env.PUBLIC_BASE_URL || "http://localhost:4000"}</p>
    `,
  });
}

export async function sendTrialRequestNotification(request: {
  schoolName: string;
  contactName: string;
  contactEmail: string;
  product?: string;
}): Promise<boolean> {
  return sendEmail({
    to: ADMIN_EMAIL,
    subject: `New Trial Request: ${request.schoolName}`,
    html: `
      <h2>New Trial Request</h2>
      <p><strong>School:</strong> ${request.schoolName}</p>
      <p><strong>Contact:</strong> ${request.contactName} (${request.contactEmail})</p>
      <p><strong>Product:</strong> ${request.product || "Not specified"}</p>
    `,
  });
}

export async function sendSafetyAlertEmail(options: {
  recipients: string[];
  studentEmail: string;
  alertType: string;
  url: string;
  title: string;
  schoolName: string;
}): Promise<number> {
  const { recipients, studentEmail, alertType, url, title, schoolName } = options;
  const alertLabel = alertType.charAt(0).toUpperCase() + alertType.slice(1).replace("-", " ");
  const subject = `⚠️ Safety Alert: ${alertLabel} detected — ${schoolName}`;
  const html = `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #dc2626;">⚠️ AI Safety Alert</h2>
      <p>ClassPilot detected potentially dangerous content on a student device.</p>
      <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
        <tr><td style="padding: 8px; font-weight: bold; border-bottom: 1px solid #e5e7eb;">Alert Type</td><td style="padding: 8px; border-bottom: 1px solid #e5e7eb; color: #dc2626;">${alertLabel}</td></tr>
        <tr><td style="padding: 8px; font-weight: bold; border-bottom: 1px solid #e5e7eb;">Student</td><td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${studentEmail}</td></tr>
        <tr><td style="padding: 8px; font-weight: bold; border-bottom: 1px solid #e5e7eb;">Page Title</td><td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${title || "Unknown"}</td></tr>
        <tr><td style="padding: 8px; font-weight: bold; border-bottom: 1px solid #e5e7eb;">URL</td><td style="padding: 8px; border-bottom: 1px solid #e5e7eb; word-break: break-all;">${url}</td></tr>
        <tr><td style="padding: 8px; font-weight: bold;">Time</td><td style="padding: 8px;">${new Date().toLocaleString("en-US", { timeZone: "America/New_York" })}</td></tr>
      </table>
      <p style="color: #6b7280; font-size: 14px;">This alert was generated by ClassPilot's AI content classification system. Please review and take appropriate action.</p>
      <p style="color: #6b7280; font-size: 12px;">To disable these emails, go to Admin Settings → AI Safety Alert Emails.</p>
    </div>
  `;

  let sent = 0;
  for (const to of recipients) {
    const ok = await sendEmail({ to, subject, html });
    if (ok) sent++;
  }
  console.log(`[Email] Safety alert sent to ${sent}/${recipients.length} recipients`);
  return sent;
}

export async function sendBroadcastEmail(recipients: string[], subject: string, message: string): Promise<number> {
  let sent = 0;
  for (const to of recipients) {
    const ok = await sendEmail({ to, subject, html: message });
    if (ok) sent++;
  }
  return sent;
}
