import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { FALLBACK, hash, inventoryFor, renderRequest, assertOnlyImageIdentityChanged, validateImageEvidence, validateCleanupCustody, validatePublishedTag, validateAnchorEvidence, createPlan, registerInactive, registrationEnvironmentProjection, anchor128Stages, renderAnchor128Pair, assertOnlyAnchorAdmissionChanged, createAnchor128Plan, registerAnchor128Inactive, validateSourceResponse } from '../scripts/register-compatible-fallback-inactive.mjs';
import { renderUnused121Pair } from '../scripts/prepare-release-artifacts.mjs';
import { SCANNER } from '../scripts/verify-legacy-deploy-image.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourceImage = `sha256:${'7'.repeat(64)}`, targetImage = `sha256:${'8'.repeat(64)}`;
const fixedNow = Date.parse('2026-10-04T16:00:00Z');
// Sanitized production serialization: the same 121 admitted names, with the
// observed zero-based positions 72 and 74 reversed. No production identifiers.
function observedAdmissionOrder(tables = anchor128Stages()[0]) {
  const value = [...tables];
  assert.equal(value[72], 'classpilot_evidence_capture_requests');
  assert.equal(value[74], 'passpilot_kiosk_sessions');
  [value[72], value[74]] = [value[74], value[72]];
  return value;
}
function definition(role, count = 129) {
  const family = role === 'api' ? 'schoolpilot-production-api-emergency' : 'schoolpilot-production-scheduler-worker';
  return { taskDefinition: { taskDefinitionArn: `arn:aws:ecs:us-east-1:135775632425:task-definition/${family}:200`, family, status: 'ACTIVE', revision: 200, registeredBy: 'synthetic', registeredAt: 'synthetic', networkMode: 'awsvpc', requiresCompatibilities: ['FARGATE'], cpu: role === 'api' ? '1024' : '512', memory: role === 'api' ? '2048' : '1024', executionRoleArn: 'synthetic-execution-role', taskRoleArn: 'synthetic-task-role', volumes: [], runtimePlatform: { cpuArchitecture: 'X86_64', operatingSystemFamily: 'LINUX' }, containerDefinitions: [{ name: role, image: `135775632425.dkr.ecr.us-east-1.amazonaws.com/schoolpilot-production-api@${sourceImage}`, cpu: 0, essential: true, command: ['node', role === 'api' ? 'dist/index.js' : 'dist/worker.js'], logConfiguration: { logDriver: 'awslogs', options: { 'awslogs-group': 'synthetic' } }, secrets: [{ name: 'DATABASE_URL', valueFrom: 'synthetic-secret-ref' }], environment: Object.entries({ GIT_SHA: FALLBACK.application, SERVICE_NAME: role, RLS_GUC_ENABLED: 'true', RLS_ENABLED_TABLES: inventoryFor(count).join(','), CLASSPILOT_USAGE_ROLLUP_MODE: 'off', CLASSPILOT_DIGITAL_USAGE_MODE: 'off', CLASSPILOT_CAP_PRECISE_RESTRICTION_RESOURCES_V1: 'false', CLASSPILOT_CAP_FOCUS_TAB_V1: 'false', CLASSPILOT_CAP_PRIVATE_CHAT_LIFECYCLE_V1: 'false', CLASSPILOT_CAP_SCOPED_AUTHORITY_CHECKS_V1: 'true', CLASSPILOT_CAPABILITY_ROLLOUTS_JSON: JSON.stringify({ scopedAuthorityChecksV1: { mode: 'on', schoolIds: [] }, privateChatLifecycleV1: { mode: 'off' } }), DB_POOL_MAX: '20', SCHEDULER_DB_POOL_MAX: '5', UNRELATED_VALUE: 'preserve-me' }).map(([name, value]) => ({ name, value })) }] }, tags: [{ key: 'Project', value: 'SchoolPilot' }] };
}
function setEnv(value, name, valueToSet) { const entry = value.taskDefinition.containerDefinitions[0].environment.find(item => item.name === name); if (valueToSet === undefined) value.taskDefinition.containerDefinitions[0].environment = value.taskDefinition.containerDefinitions[0].environment.filter(item => item.name !== name); else entry.value = valueToSet; }
function stamp(request, role) { const container = request.containerDefinitions.find(item => item.name === role); container.environment = [...container.environment.filter(item => !['GIT_SHA', 'SERVICE_NAME'].includes(item.name)), { name: 'SERVICE_NAME', value: role }, { name: 'GIT_SHA', value: FALLBACK.source }]; }
function imageEvidence() { return { scan: { schemaVersion: 1, passed: true, sourceSha: FALLBACK.source, imageId: FALLBACK.localIndex, configDigest: FALLBACK.config, scanner: SCANNER, os: 'linux', architecture: 'amd64', counts: { HIGH: 0, CRITICAL: 0 } }, proof: { schemaVersion: 1, passed: true, sourceSha: FALLBACK.source, configDigest: FALLBACK.config, platformDigest: FALLBACK.platform, digest: targetImage, scanner: SCANNER, repository: FALLBACK.repository, region: FALLBACK.region } }; }
function fixture() {
  const directory = mkdtempSync(path.join(os.tmpdir(), 'sp297-inactive-pure-')); const inputDirectory = path.join(directory, 'input'); mkdirSync(inputDirectory);
  const record = (name, value, bytes) => { const filename = path.join(inputDirectory, name); const data = bytes ?? Buffer.from(JSON.stringify(value, null, 2) + '\n'); writeFileSync(filename, data); return { path: filename, sha256: hash(data) }; };
  const { scan, proof } = imageEvidence(), scanRecord = record('scan.json', scan); proof.receiptSha256 = scanRecord.sha256;
  const services = { services: [{ serviceName: 'schoolpilot-production-api', taskDefinition: 'synthetic-old-api', desiredCount: 1 }, { serviceName: 'schoolpilot-production-scheduler-worker', taskDefinition: 'synthetic-old-worker', desiredCount: 1 }], failures: [] };
  const input = { schemaVersion: 1, outputDirectory: path.join(directory, 'plan'), anchorDirectory: path.join(directory, 'anchor'), fallbackDirectory: path.join(directory, 'fallback'), anchorSource: FALLBACK.application, anchorImage: sourceImage, admissionCount: 129, api: record('api.json', definition('api')), worker: record('worker.json', definition('scheduler-worker')), liveServices: record('services.json', services), scan: scanRecord, registryProof: record('registry.json', proof), publishedTag: record('tag.json', { imageDetails: [{ registryId: FALLBACK.account, repositoryName: FALLBACK.repository, imageDigest: targetImage, imageTags: [FALLBACK.tag] }] }), scanCleanup: record('cleanup-custody.json', { schemaVersion: 1, complete: true, forced: false, exactOwned: true, scannerExitCode: 0, ownedScannerAbsent: true, ownedScanner: 'schoolpilot-image-scan-1234', scanSha256: scanRecord.sha256 }), syntheticStage: record('stage.json', null, readFileSync(path.join(root, 'docs/release-evidence/release-297/release-gate-policy-20261003/staging128129-ddc5996b-passed.json'))) };
  const anchorConfig = `sha256:${'6'.repeat(64)}`, anchorPlatform = `sha256:${'5'.repeat(64)}`;
  input.anchorScan = record('anchor-scan.json', { ...scan, sourceSha: FALLBACK.application, configDigest: anchorConfig, imageId: sourceImage });
  input.anchorRegistryProof = record('anchor-registry.json', { ...proof, sourceSha: FALLBACK.application, configDigest: anchorConfig, platformDigest: anchorPlatform, digest: sourceImage, receiptSha256: input.anchorScan.sha256 });
  input.anchorPublishedTag = record('anchor-tag.json', { imageDetails: [{ registryId: FALLBACK.account, repositoryName: FALLBACK.repository, imageDigest: sourceImage, imageTags: [FALLBACK.application.slice(0, 12)] }] });
  const commands = [], registered = new Map(); const behavior = { tagDigest: targetImage, failWorker: false, afterServicesChanged: false, sourceDiff: '', dirty: false, clock: fixedNow, expireDuringSourceGet: false, registeredMutation: undefined };
  let serviceReads = 0;
  const run = async (executable, args) => {
    commands.push({ executable, args }); const success = value => ({ code: 0, stdout: typeof value === 'string' ? value : JSON.stringify(value), stderr: '' });
    if (executable === 'git') { const cwd = args[1], operation = args[2]; if (operation === 'rev-parse') return success(cwd === input.fallbackDirectory ? FALLBACK.source : FALLBACK.application); if (operation === 'status') return success(behavior.dirty ? ' M synthetic' : ''); if (operation === 'diff') return success(behavior.sourceDiff); if (operation === 'show') { if (args[3].endsWith('classpilotProtocol.ts')) return success(readFileSync(path.join(root, 'src/services/classpilotProtocol.ts'), 'utf8')); return success(args[3].endsWith('websocket.ts') ? 'export const PRIVATE_CHAT_RELAY_VERSION = 1;' : 'export const PRIVATE_CHAT_LIFECYCLE_WRITER_VERSION = 1; export const PRIVATE_CHAT_BRIDGE_VERSION = 1;'); } }
    if (executable === 'pwsh') return success('');
    if (executable === process.execPath) { const filename = args[args.indexOf('--task-definition') + 1], role = args[args.indexOf('--service') + 1]; const value = JSON.parse(readFileSync(filename)); stamp(value, role); writeFileSync(filename, JSON.stringify(value)); return success(''); }
    if (executable === 'aws') {
      const [service, operation] = args;
      if (service === 'sts') return success({ Account: FALLBACK.account });
      if (service === 'ecr') { const anchor = args.includes(`imageTag=${FALLBACK.application.slice(0, 12)}`); return success({ imageDetails: [{ registryId: FALLBACK.account, repositoryName: FALLBACK.repository, imageDigest: anchor ? sourceImage : behavior.tagDigest, imageTags: [anchor ? FALLBACK.application.slice(0, 12) : FALLBACK.tag] }] }); }
      if (operation === 'describe-services') { serviceReads++; return success(behavior.afterServicesChanged && serviceReads > 1 ? { ...services, services: [...services.services].reverse() } : services); }
      if (operation === 'register-task-definition') { const filename = args[args.indexOf('--cli-input-json') + 1].slice('file://'.length); const request = JSON.parse(readFileSync(filename)); const role = request.containerDefinitions[0].name; if (behavior.failWorker && role === 'scheduler-worker') return { code: 1, stdout: '', stderr: 'synthetic transport failure' }; const value = { taskDefinition: { ...structuredClone(request), status: 'ACTIVE', revision: 201, taskDefinitionArn: `arn:aws:ecs:us-east-1:135775632425:task-definition/${request.family}:201` }, tags: request.tags }; delete value.taskDefinition.tags; registered.set(value.taskDefinition.taskDefinitionArn, value); return success(value); }
      if (operation === 'describe-task-definition') { const arn = args[args.indexOf('--task-definition') + 1]; if (behavior.expireDuringSourceGet && arn.endsWith(':200')) behavior.clock = fixedNow + 400_000; const value = registered.has(arn) ? structuredClone(registered.get(arn)) : JSON.parse(readFileSync(arn.includes('api-emergency') ? input.api.path : input.worker.path)); if (registered.has(arn)) behavior.registeredMutation?.(value); return success(value); }
    }
    throw new Error('UNEXPECTED_PURE_COMMAND');
  };
  const clean = () => { const resolved = path.resolve(directory), prefix = path.resolve(os.tmpdir()) + path.sep; assert.ok(resolved.startsWith(prefix) && path.basename(resolved).startsWith('sp297-inactive-pure-')); rmSync(resolved, { recursive: true }); };
  const options = { run, now: () => behavior.clock, verifyLocalScan: async () => {}, verifyRegistry: async (_plan, _run, arm) => arm === 'anchor' ? { digest: sourceImage, configDigest: anchorConfig, platformDigest: anchorPlatform } : { digest: targetImage, configDigest: FALLBACK.config, platformDigest: FALLBACK.platform } };
  const authorization = plan => record('authorization.json', { schemaVersion: 1, operation: 'RegisterInactive', authorized: true, planSha256: plan.sha256, startsAtUtc: new Date(fixedNow - 1000).toISOString(), expiresAtUtc: new Date(fixedNow + 300_000).toISOString() });
  return { directory, input, run, commands, behavior, clean, record, options, authorization };
}

test('exact128 and129 inventories remain append-only', () => { assert.equal(inventoryFor(128).length, 128); assert.equal(inventoryFor(129).at(-1), 'classpilot_private_chat_threads'); assert.deepEqual(inventoryFor(129).slice(0, 128), inventoryFor(128)); assert.throws(() => inventoryFor(121), /EXACT_COMPATIBLE_FLOOR_REQUIRED/); });
test('render preserves tags sidecars roles network commands and unrelated environment', () => { const original = definition('api'); original.taskDefinition.containerDefinitions.unshift({ name: 'synthetic-sidecar', image: 'synthetic-sidecar-image', essential: false, environment: [] }); const rendered = renderRequest(original, 'api', FALLBACK.application, sourceImage, targetImage, 129); stamp(rendered, 'api'); assertOnlyImageIdentityChanged(original, rendered, 'api', targetImage); assert.equal(original.taskDefinition.containerDefinitions[1].image.endsWith(sourceImage), true); assert.deepEqual(rendered.tags, original.tags); assert.deepEqual(rendered.containerDefinitions[0], original.taskDefinition.containerDefinitions[0]); });
test('old production source cannot become compatible fallback anchor', () => assert.throws(() => renderRequest(definition('api'), 'api', '7af9d0dd5bc2bd3e13b96d35a577725e07f8b678', sourceImage, targetImage, 129), /COMPATIBLE_CANDIDATE_ANCHOR_REQUIRED/));
test('resource or hard-memory reduction rejects rendering', () => { for (const change of [value => { value.taskDefinition.cpu = '512'; }, value => { value.taskDefinition.containerDefinitions[0].memory = 1024; }]) { const value = definition('api'); change(value); assert.throws(() => renderRequest(value, 'api', FALLBACK.application, sourceImage, targetImage, 129), /SOURCE_.*DRIFT/); } });
test('wrong role or image identity rejects rendering', () => { const value = definition('api'); assert.throws(() => renderRequest(value, 'scheduler-worker', FALLBACK.application, sourceImage, targetImage, 129)); assert.throws(() => renderRequest(value, 'api', FALLBACK.application, targetImage, targetImage, 129), /SOURCE_IMAGE_DRIFT/); });
test('missing or narrowed tenant admission rejects rendering', () => { const value = definition('api'); setEnv(value, 'RLS_ENABLED_TABLES', inventoryFor(128).join(',')); assert.throws(() => renderRequest(value, 'api', FALLBACK.application, sourceImage, targetImage, 129), /ADMISSION_DRIFT/); setEnv(value, 'RLS_GUC_ENABLED', 'false'); assert.throws(() => renderRequest(value, 'api', FALLBACK.application, sourceImage, targetImage, 128), /TENANT_GUC_REQUIRED/); });
test('both Usage modes must explicitly remain off', () => { for (const name of ['CLASSPILOT_USAGE_ROLLUP_MODE', 'CLASSPILOT_DIGITAL_USAGE_MODE']) for (const next of ['on', undefined]) { const value = definition('api'); setEnv(value, name, next); assert.throws(() => renderRequest(value, 'api', FALLBACK.application, sourceImage, targetImage, 129), /USAGE_MUST_BE_EXPLICITLY_OFF/); } });
test('all three new classroom issuance controls remain off', () => { for (const name of ['CLASSPILOT_CAP_PRECISE_RESTRICTION_RESOURCES_V1', 'CLASSPILOT_CAP_FOCUS_TAB_V1', 'CLASSPILOT_CAP_PRIVATE_CHAT_LIFECYCLE_V1']) { const value = definition('api'); setEnv(value, name, 'true'); assert.throws(() => renderRequest(value, 'api', FALLBACK.application, sourceImage, targetImage, 129), /NEW_ISSUANCE_MUST_BE_OFF/); } const value = definition('api'); setEnv(value, 'CLASSPILOT_CAPABILITY_ROLLOUTS_JSON', '{"focusTabV1":{"mode":"on"}}'); assert.throws(() => renderRequest(value, 'api', FALLBACK.application, sourceImage, targetImage, 129), /NEW_ROLLOUT_MUST_BE_OFF/); });
test('duplicate names and secret control overrides reject rendering', () => { const value = definition('api'); value.taskDefinition.containerDefinitions[0].environment.push({ name: 'GIT_SHA', value: 'synthetic' }); assert.throws(() => renderRequest(value, 'api', FALLBACK.application, sourceImage, targetImage, 129), /DUPLICATE_RUNTIME_NAME/); const other = definition('api'); other.taskDefinition.containerDefinitions[0].secrets.push({ name: 'CLASSPILOT_CAP_FOCUS_TAB_V1', valueFrom: 'synthetic' }); assert.throws(() => renderRequest(other, 'api', FALLBACK.application, sourceImage, targetImage, 129)); });
test('unknown task field cannot be silently dropped', () => { const value = definition('api'); value.taskDefinition.unreviewedFutureField = true; assert.throws(() => renderRequest(value, 'api', FALLBACK.application, sourceImage, targetImage, 129), /UNKNOWN_TASK_FIELD/); });
test('structural replay rejects unrelated field or sidecar mutation', () => { for (const change of [value => { value.taskRoleArn = 'changed'; }, value => { value.containerDefinitions[0].environment.find(item => item.name === 'DB_POOL_MAX').value = '32'; }, value => { value.tags.push({ key: 'unexpected', value: 'change' }); }]) { const source = definition('api'), value = renderRequest(source, 'api', FALLBACK.application, sourceImage, targetImage, 129); stamp(value, 'api'); change(value); assert.throws(() => assertOnlyImageIdentityChanged(source, value, 'api', targetImage), /UNRELATED_TASK_MUTATION/); } });
test('scan and registry identities cannot confuse local index platform and config', () => { const { scan, proof } = imageEvidence(); validateImageEvidence(scan, proof); for (const key of ['imageId', 'configDigest']) { const wrong = structuredClone(scan); wrong[key] = FALLBACK.platform; assert.throws(() => validateImageEvidence(wrong, proof)); } const wrong = structuredClone(proof); wrong.platformDigest = FALLBACK.localIndex; assert.throws(() => validateImageEvidence(scan, wrong), /FALLBACK_PLATFORM_CHANGED/); });
test('published tag requires exact account repository source tag and resolved digest', () => { const correct = { imageDetails: [{ registryId: FALLBACK.account, repositoryName: FALLBACK.repository, imageDigest: targetImage, imageTags: [FALLBACK.tag] }] }; validatePublishedTag(correct, targetImage); for (const update of [{ registryId: '000000000000' }, { repositoryName: 'other' }, { imageTags: [FALLBACK.source] }, { imageDigest: sourceImage }]) assert.throws(() => validatePublishedTag({ imageDetails: [{ ...correct.imageDetails[0], ...update }] }, targetImage)); });
test('anchor image requires source-bound scan registry and tag rather than environment identity alone', () => { const f = fixture(); try { const scan = JSON.parse(readFileSync(f.input.anchorScan.path)), proof = JSON.parse(readFileSync(f.input.anchorRegistryProof.path)), tag = JSON.parse(readFileSync(f.input.anchorPublishedTag.path)); validateAnchorEvidence(f.input, scan, proof, tag); for (const update of [{ sourceSha: FALLBACK.source }, { receiptSha256: 'a'.repeat(64) }, { configDigest: FALLBACK.config }, { digest: targetImage }]) assert.throws(() => validateAnchorEvidence(f.input, scan, { ...proof, ...update }, tag)); } finally { f.clean(); } });
test('unfixed blocking scan findings and forced or uncertain cleanup reject', () => { const { scan, proof } = imageEvidence(); scan.counts.HIGH = 1; assert.throws(() => validateImageEvidence(scan, proof), /BLOCKING_SCAN_FINDINGS/); const sha = 'a'.repeat(64), record = { schemaVersion: 1, complete: true, forced: false, exactOwned: true, scannerExitCode: 0, ownedScannerAbsent: true, ownedScanner: 'schoolpilot-image-scan-1234', scanSha256: sha }; validateCleanupCustody(sha, record); for (const update of [{ forced: true }, { complete: false }, { scannerExitCode: 1 }, { scanSha256: 'b'.repeat(64) }]) assert.throws(() => validateCleanupCustody(sha, { ...record, ...update })); });
test('offline Plan reuses identity and private-permission helpers without AWS', async () => { const f = fixture(); try { const plan = await createPlan(f.input, f.options); assert.equal(plan.registered, false); assert.equal(f.commands.some(value => value.executable === 'aws'), false); assert.equal(f.commands.filter(value => value.executable === process.execPath).length, 2); assert.equal(f.commands.filter(value => value.executable === 'pwsh').length, 1); const value = JSON.parse(readFileSync(plan.path)); assert.equal(value.cloudMutationsDuringPlan, 0); assert.equal(value.generated.api.request.containerDefinitions[0].environment.find(item => item.name === 'GIT_SHA').value, FALLBACK.source); } finally { f.clean(); } });
test('Plan rejects changed DDC application bytes and mismatched source pair controls', async () => { const f = fixture(); try { f.behavior.sourceDiff = 'src/app.ts'; await assert.rejects(createPlan(f.input, f.options), /ANCHOR_APPLICATION_BYTES_CHANGED/); f.behavior.sourceDiff = ''; const value = JSON.parse(readFileSync(f.input.worker.path)); setEnv(value, 'CLASSPILOT_CAP_SCOPED_AUTHORITY_CHECKS_V1', 'false'); f.input.worker = f.record('worker-changed.json', value); await assert.rejects(createPlan(f.input, f.options), /PAIR_CAPABILITY_MISMATCH/); } finally { f.clean(); } });
test('registration emits exactly two inactive definitions and preserves services', async () => { const f = fixture(); try { const plan = await createPlan(f.input, f.options), authorization = f.authorization(plan); const result = await registerInactive(plan, authorization, f.options); assert.equal(result.registered.length, 2); assert.equal(result.servicesUpdated, 0); assert.equal(result.tasksLaunched, 0); const mutations = f.commands.filter(value => value.executable === 'aws' && ['register-task-definition', 'update-service', 'run-task', 'register-scalable-target', 'deregister-task-definition'].includes(value.args[1])); assert.deepEqual(mutations.map(value => value.args[1]), ['register-task-definition', 'register-task-definition']); await assert.rejects(registerInactive(plan, authorization, f.options), /PLAN_ALREADY_USED/); } finally { f.clean(); } });
test('source tag conflict blocks before any registration', async () => { const f = fixture(); try { const plan = await createPlan(f.input, f.options); f.behavior.tagDigest = sourceImage; await assert.rejects(registerInactive(plan, f.authorization(plan), f.options), /SOURCE_TAG_CONFLICT/); assert.equal(f.commands.some(value => value.args[1] === 'register-task-definition'), false); } finally { f.clean(); } });
test('expired or rebound authorization blocks before cloud mutation', async () => { const f = fixture(); try { const plan = await createPlan(f.input, f.options); const expired = f.record('expired.json', { schemaVersion: 1, operation: 'RegisterInactive', authorized: true, planSha256: plan.sha256, startsAtUtc: new Date(fixedNow - 10_000).toISOString(), expiresAtUtc: new Date(fixedNow - 1000).toISOString() }); await assert.rejects(registerInactive(plan, expired, f.options), /AUTHORIZED_WINDOW_EXPIRED/); const rebound = f.record('rebound.json', { schemaVersion: 1, operation: 'RegisterInactive', authorized: true, planSha256: 'a'.repeat(64), startsAtUtc: new Date(fixedNow - 1000).toISOString(), expiresAtUtc: new Date(fixedNow + 1000).toISOString() }); await assert.rejects(registerInactive(plan, rebound, f.options), /EXACT_AUTHORIZATION_REQUIRED/); assert.equal(f.commands.some(value => value.executable === 'aws'), false); } finally { f.clean(); } });
test('source GET exhausting the authorization window cannot register any definition', async () => { const f = fixture(); try { const plan = await createPlan(f.input, f.options); f.behavior.expireDuringSourceGet = true; await assert.rejects(registerInactive(plan, f.authorization(plan), f.options), /COMPATIBLE_INACTIVE_REGISTRATION_FAILED/); assert.equal(f.commands.some(value => value.args[1] === 'register-task-definition'), false); const receipt = JSON.parse(readFileSync(path.join(f.input.outputDirectory, 'registration.private.json'))); assert.equal(receipt.registered.length, 0); } finally { f.clean(); } });
test('changed generated request blocks before registration', async () => { const f = fixture(); try { const plan = await createPlan(f.input, f.options), value = JSON.parse(readFileSync(plan.path)); writeFileSync(value.generated.api.path, '{}'); await assert.rejects(registerInactive(plan, f.authorization(plan), f.options), /GENERATED_REQUEST_CHANGED|COMPATIBLE_INACTIVE_REGISTRATION_FAILED/); assert.equal(f.commands.some(value => value.args[1] === 'register-task-definition'), false); } finally { f.clean(); } });
test('partial registration retains inactive ARN and uncertainty without service rollback', async () => { const f = fixture(); try { const plan = await createPlan(f.input, f.options); f.behavior.failWorker = true; await assert.rejects(registerInactive(plan, f.authorization(plan), f.options), /COMPATIBLE_INACTIVE_REGISTRATION_FAILED/); const receipt = JSON.parse(readFileSync(path.join(f.input.outputDirectory, 'registration.private.json'))); assert.equal(receipt.status, 'failed_retained_inactive'); assert.equal(receipt.registered.length, 1); assert.equal(receipt.registrationOutcomeUncertain, true); assert.equal(f.commands.some(value => ['update-service', 'deregister-task-definition'].includes(value.args[1])), false); } finally { f.clean(); } });
test('post-registration service drift seals failure rather than acceptance', async () => { const f = fixture(); try { const plan = await createPlan(f.input, f.options); f.behavior.afterServicesChanged = true; await assert.rejects(registerInactive(plan, f.authorization(plan), f.options), /COMPATIBLE_INACTIVE_REGISTRATION_FAILED/); assert.equal(JSON.parse(readFileSync(path.join(f.input.outputDirectory, 'registration.private.json'))).status, 'failed_retained_inactive'); } finally { f.clean(); } });
test('actual tagged registration response may reorder exact environment bindings', async () => { const f = fixture(); try { const plan = await createPlan(f.input, f.options); f.behavior.registeredMutation = value => value.taskDefinition.containerDefinitions[0].environment.reverse(); const result = await registerInactive(plan, f.authorization(plan), f.options); assert.equal(result.registered.length, 2); assert.equal(result.servicesUpdated, 0); assert.equal(JSON.parse(readFileSync(result.receiptPath)).status, 'registered_inactive'); } finally { f.clean(); } });
test('environment projection copies both containers and preserves every other array and value', () => { const value = renderRequest(definition('api'), 'api', FALLBACK.application, sourceImage, targetImage, 129); stamp(value, 'api'); value.containerDefinitions.unshift({ name: 'synthetic-sidecar', environment: [{ name: 'z', value: 'unchanged-z' }, { name: 'A', value: 'unchanged-A' }], command: ['second', 'first'], secrets: [{ name: 'z', valueFrom: 'second' }, { name: 'A', valueFrom: 'first' }] }); const before = structuredClone(value), actual = registrationEnvironmentProjection(value); assert.deepEqual(value, before); assert.deepEqual(actual.containerDefinitions[0].environment, [...before.containerDefinitions[0].environment].reverse()); for (let index = 0; index < actual.containerDefinitions.length; index++) { const changed = { ...actual.containerDefinitions[index] }; delete changed.environment; const original = { ...before.containerDefinitions[index] }; delete original.environment; assert.deepEqual(changed, original); } assert.deepEqual(actual.tags, before.tags); });
test('duplicate changed or removed actual environment bindings reject inactive acceptance', async () => { for (const mutation of [value => { const entries = value.taskDefinition.containerDefinitions[0].environment; entries.push(structuredClone(entries[0])); }, value => { value.taskDefinition.containerDefinitions[0].environment.find(entry => entry.name === 'UNRELATED_VALUE').value = 'changed'; }, value => { value.taskDefinition.containerDefinitions[0].environment = value.taskDefinition.containerDefinitions[0].environment.filter(entry => entry.name !== 'UNRELATED_VALUE'); }]) { const f = fixture(); try { const plan = await createPlan(f.input, f.options); f.behavior.registeredMutation = mutation; await assert.rejects(registerInactive(plan, f.authorization(plan), f.options), /COMPATIBLE_INACTIVE_REGISTRATION_FAILED/); const receipt = JSON.parse(readFileSync(path.join(f.input.outputDirectory, 'registration.private.json'))); assert.equal(receipt.status, 'failed_retained_inactive'); assert.equal(receipt.registered.length, 1); assert.equal(f.commands.some(value => ['update-service', 'run-task', 'deregister-task-definition'].includes(value.args[1])), false); } finally { f.clean(); } } });
test('tag command secret and sidecar environment mutations remain different or rejected', () => { const value = renderRequest(definition('api'), 'api', FALLBACK.application, sourceImage, targetImage, 129); stamp(value, 'api'); for (const mutate of [copy => { delete copy.tags; }, copy => { copy.tags[0].value = 'changed'; }, copy => { copy.containerDefinitions[0].command.reverse(); }, copy => { copy.containerDefinitions[0].secrets[0].valueFrom = 'changed'; }]) { const copy = structuredClone(value); mutate(copy); assert.notDeepEqual(registrationEnvironmentProjection(copy), registrationEnvironmentProjection(value)); } const sidecar = structuredClone(value); sidecar.containerDefinitions.push({ name: 'synthetic-sidecar', environment: [{ name: 'x', value: 'one' }, { name: 'x', value: 'two' }] }); assert.throws(() => registrationEnvironmentProjection(sidecar), /REGISTERED_ENVIRONMENT_INVALID/); const missingValue = structuredClone(value); delete missingValue.containerDefinitions[0].environment[0].value; assert.throws(() => registrationEnvironmentProjection(missingValue), /REGISTERED_ENVIRONMENT_INVALID/); });

function anchor121(role) { const value = definition(role); setEnv(value, 'RLS_ENABLED_TABLES', anchor128Stages()[0].join(',')); return value; }
function anchorFixture() {
  const f = fixture();
  f.input.api = f.record('anchor121-api.json', anchor121('api')); f.input.worker = f.record('anchor121-worker.json', anchor121('scheduler-worker'));
  f.input.anchorScanCleanup = f.record('anchor-scan-custody.json', { schemaVersion: 1, complete: true, forced: false, exactOwned: true, scannerExitCode: 0, ownedScannerAbsent: true, ownedScanner: 'schoolpilot-image-scan-1234', scanSha256: f.input.anchorScan.sha256 });
  const original = f.run; f.options.run = async (executable, args, options) => {
    const result = await original(executable, args, options);
    if (executable === 'aws' && args[1] === 'describe-task-definition' && args[args.indexOf('--task-definition') + 1].endsWith(':200') && f.behavior.anchorSourceMutation) { const value = JSON.parse(result.stdout); f.behavior.anchorSourceMutation(value); return { ...result, stdout: JSON.stringify(value) }; }
    if (executable === 'aws' && args[0] === 'ecr' && args[1] === 'describe-images' && f.behavior.anchorTagConflict) { const value = JSON.parse(result.stdout); value.imageDetails[0].imageDigest = targetImage; return { ...result, stdout: JSON.stringify(value) }; }
    if (executable === 'aws' && args[1] === 'register-task-definition' && f.behavior.expireAfterMutation) f.behavior.clock = fixedNow + 400_000;
    return result;
  };
  f.options.verifyRegistry = async () => ({ digest: sourceImage, configDigest: `sha256:${'6'.repeat(64)}`, platformDigest: `sha256:${'5'.repeat(64)}` });
  f.authorization = plan => f.record('anchor-authorization.json', { schemaVersion: 1, operation: 'RegisterInactiveAnchor128', authorized: true, planSha256: plan.sha256, startsAtUtc: new Date(fixedNow - 1000).toISOString(), expiresAtUtc: new Date(fixedNow + 300_000).toISOString() });
  return f;
}
test('anchor uses exactly the ordered121 125 126 127 128 reviewed inventories', () => { const stages = anchor128Stages(); assert.deepEqual(stages.map(value => value.length), [121, 125, 126, 127, 128]); assert.deepEqual(stages[1].slice(121), ['passpilot_destination_policies', 'passpilot_pass_limits', 'passpilot_encounter_restrictions', 'passpilot_pass_denials']); assert.deepEqual(stages[4], inventoryFor(128)); const returned = anchor128Stages(); returned[0].reverse(); assert.notDeepEqual(returned[0], anchor128Stages()[0]); });
test('anchor rendering changes only admission preserving source image tags sidecars and every other field', () => { const sources = { api: anchor121('api'), 'scheduler-worker': anchor121('scheduler-worker') }; sources.api.taskDefinition.containerDefinitions.unshift({ name: 'synthetic-sidecar', image: 'synthetic-other-image', command: ['unchanged', 'order'], environment: [{ name: 'sidecar', value: 'preserved' }], secrets: [] }); const before = structuredClone(sources), requests = renderAnchor128Pair(sources, FALLBACK.application, sourceImage); assert.deepEqual(sources, before); for (const role of ['api', 'scheduler-worker']) { assertOnlyAnchorAdmissionChanged(sources[role], requests[role], role, FALLBACK.application, sourceImage); const original = sources[role].taskDefinition.containerDefinitions.find(value => value.name === role), actual = requests[role].containerDefinitions.find(value => value.name === role); assert.equal(actual.image, original.image); assert.equal(actual.environment.find(value => value.name === 'GIT_SHA').value, FALLBACK.application); } assert.deepEqual(requests.api.containerDefinitions[0], sources.api.taskDefinition.containerDefinitions[0]); });
test('anchor rejects old source bad digest duplicate121 and narrowed admission', () => { const sources = { api: anchor121('api'), 'scheduler-worker': anchor121('scheduler-worker') }; for (const source of ['7af9d0dd5bc2bd3e13b96d35a577725e07f8b678', FALLBACK.source]) assert.throws(() => renderAnchor128Pair(sources, source, sourceImage)); assert.throws(() => renderAnchor128Pair(sources, FALLBACK.application, targetImage), /SOURCE_IMAGE_DRIFT/); for (const tables of [anchor128Stages()[0].map((table, index, tables) => index === 72 ? tables[74] : table), anchor128Stages()[0].slice(1), inventoryFor(128)]) { const copy = structuredClone(sources); setEnv(copy.api, 'RLS_ENABLED_TABLES', tables.join(',')); assert.throws(() => renderAnchor128Pair(copy, FALLBACK.application, sourceImage), /ADMISSION_DRIFT/); } });
test('anchor rejects Usage issuance resource pair and secret control drift', () => { for (const mutate of [value => setEnv(value, 'CLASSPILOT_DIGITAL_USAGE_MODE', 'on'), value => setEnv(value, 'CLASSPILOT_CAP_FOCUS_TAB_V1', 'true'), value => { value.taskDefinition.cpu = '2048'; }, value => { value.taskDefinition.containerDefinitions[0].secrets.push({ name: 'RLS_ENABLED_TABLES', valueFrom: 'synthetic' }); }, value => setEnv(value, 'CLASSPILOT_CAP_SCOPED_AUTHORITY_CHECKS_V1', 'false')]) { const sources = { api: anchor121('api'), 'scheduler-worker': anchor121('scheduler-worker') }; mutate(sources.api); assert.throws(() => renderAnchor128Pair(sources, FALLBACK.application, sourceImage)); } });
test('anchor structural fence rejects image stamp command tag secret sidecar or pool changes', () => { const source = anchor121('api'); source.taskDefinition.containerDefinitions.push({ name: 'synthetic-sidecar', image: 'unchanged', environment: [] }); const request = renderAnchor128Pair({ api: source, 'scheduler-worker': anchor121('scheduler-worker') }, FALLBACK.application, sourceImage).api; for (const mutate of [copy => { copy.containerDefinitions[0].image = 'changed'; }, copy => { copy.containerDefinitions[0].environment.find(entry => entry.name === 'GIT_SHA').value = FALLBACK.source; }, copy => { copy.containerDefinitions[0].command.reverse(); }, copy => { copy.tags.reverse(); copy.tags.push({ key: 'added', value: 'changed' }); }, copy => { copy.containerDefinitions[0].secrets[0].valueFrom = 'changed'; }, copy => { copy.containerDefinitions[1].image = 'changed'; }, copy => { copy.containerDefinitions[0].environment.find(entry => entry.name === 'DB_POOL_MAX').value = '32'; }]) { const copy = structuredClone(request); mutate(copy); assert.throws(() => assertOnlyAnchorAdmissionChanged(source, copy, 'api', FALLBACK.application, sourceImage)); } });
test('anchor offline Plan requires actual source scan custody and creates no AWS operation', async () => { const f = anchorFixture(); try { const plan = await createAnchor128Plan(f.input, f.options), value = JSON.parse(readFileSync(plan.path)); assert.equal(plan.admissionCount, 128); assert.equal(f.commands.some(entry => entry.executable === 'aws'), false); assert.equal(f.commands.some(entry => entry.executable === process.execPath), false); assert.equal(value.kind, 'compatible_anchor128_inactive'); assert.deepEqual(value.executableActions, ['RegisterInactiveAnchor128']); assert.deepEqual(value.admissionCounts, [121, 125, 126, 127, 128]); } finally { f.clean(); } });
test('anchor Plan rejects self-labelled image changed app and forced scanner cleanup', async () => { const f = anchorFixture(); try { f.behavior.sourceDiff = 'src/app.ts'; await assert.rejects(createAnchor128Plan(f.input, f.options), /ANCHOR_APPLICATION_BYTES_CHANGED/); f.behavior.sourceDiff = ''; f.input.anchorScanCleanup = f.record('bad-cleanup.json', { ...JSON.parse(readFileSync(f.input.anchorScanCleanup.path)), forced: true }); await assert.rejects(createAnchor128Plan(f.input, f.options), /UNFORCED_SCANNER_CLEANUP_REQUIRED/); } finally { f.clean(); } });
test('anchor Plan rejects sources referenced by service or draining deployment', async () => { for (const reference of ['taskDefinition', 'deployment', 'taskSet']) { const f = anchorFixture(); try { const live = JSON.parse(readFileSync(f.input.liveServices.path)), arn = JSON.parse(readFileSync(f.input.api.path)).taskDefinition.taskDefinitionArn; if (reference === 'taskDefinition') live.services[0].taskDefinition = arn; else live.services[0][reference === 'deployment' ? 'deployments' : 'taskSets'] = [{ taskDefinition: arn }]; f.input.liveServices = f.record('serving-source.json', live); await assert.rejects(createAnchor128Plan(f.input, f.options), /ANCHOR_SOURCE_IS_SERVING/); assert.equal(f.commands.some(entry => entry.executable === 'aws'), false); } finally { f.clean(); } } });
test('anchor registration performs exactly two inactive registrations and no launch update publish or migration', async () => { const f = anchorFixture(); try { const plan = await createAnchor128Plan(f.input, f.options), authorization = f.authorization(plan), result = await registerAnchor128Inactive(plan, authorization, f.options); assert.equal(result.registered.length, 2); const receipt = JSON.parse(readFileSync(result.receiptPath)); assert.equal(receipt.status, 'registered_inactive'); assert.equal(receipt.servicesUpdated + receipt.tasksLaunched + receipt.productionDatabaseOperations + receipt.imagesPublished, 0); assert.deepEqual(f.commands.filter(entry => entry.executable === 'aws' && !['get-caller-identity', 'describe-images', 'describe-services', 'describe-task-definition', 'batch-get-image'].includes(entry.args[1])).map(entry => entry.args[1]), ['register-task-definition', 'register-task-definition']); await assert.rejects(registerAnchor128Inactive(plan, authorization, f.options), /PLAN_ALREADY_USED/); } finally { f.clean(); } });
test('anchor authorization cannot reuse fallback permission or rebound expired plans', async () => { const f = anchorFixture(); try { const plan = await createAnchor128Plan(f.input, f.options), auth = JSON.parse(readFileSync(f.authorization(plan).path)); for (const update of [{ operation: 'RegisterInactive' }, { planSha256: 'f'.repeat(64) }, { expiresAtUtc: new Date(fixedNow - 1).toISOString(), startsAtUtc: new Date(fixedNow - 10_000).toISOString() }]) { const record = f.record(`wrong-auth-${Object.keys(update)[0]}.json`, { ...auth, ...update }); await assert.rejects(registerAnchor128Inactive(plan, record, f.options)); } assert.equal(f.commands.some(entry => entry.executable === 'aws'), false); } finally { f.clean(); } });
test('anchor current tag source definition and live service drift reject before registration', async () => { for (const change of ['tag', 'source', 'services']) { const f = anchorFixture(); try { const plan = await createAnchor128Plan(f.input, f.options); if (change === 'tag') f.behavior.anchorTagConflict = true; if (change === 'source') f.behavior.anchorSourceMutation = value => { value.tags.push({ key: 'unexpected', value: 'change' }); }; if (change === 'services') f.behavior.afterServicesChanged = true; if (change === 'services') { await f.options.run('aws', ['ecs', 'describe-services']); } await assert.rejects(registerAnchor128Inactive(plan, f.authorization(plan), f.options)); assert.equal(f.commands.some(entry => entry.args[1] === 'register-task-definition'), false); } finally { f.clean(); } } });
test('anchor source GET expiry blocks mutation and post-register expiry retains returned ARN', async () => { for (const phase of ['source', 'returned']) { const f = anchorFixture(); try { const plan = await createAnchor128Plan(f.input, f.options); if (phase === 'source') f.behavior.expireDuringSourceGet = true; else f.behavior.expireAfterMutation = true; await assert.rejects(registerAnchor128Inactive(plan, f.authorization(plan), f.options)); const mutations = f.commands.filter(entry => entry.args[1] === 'register-task-definition'); assert.equal(mutations.length, phase === 'source' ? 0 : 1); if (phase === 'returned') { const receipt = JSON.parse(readFileSync(path.join(f.input.outputDirectory, 'registration.private.json'))); assert.equal(receipt.registered.length, 1); assert.equal(receipt.registrationOutcomeUncertain, false); } } finally { f.clean(); } } });
test('anchor partial registration retains inactive ARN and uncertain worker without cleanup mutations', async () => { const f = anchorFixture(); try { const plan = await createAnchor128Plan(f.input, f.options); f.behavior.failWorker = true; await assert.rejects(registerAnchor128Inactive(plan, f.authorization(plan), f.options), /COMPATIBLE_ANCHOR128_REGISTRATION_FAILED/); const receipt = JSON.parse(readFileSync(path.join(f.input.outputDirectory, 'registration.private.json'))); assert.equal(receipt.status, 'failed_retained_inactive'); assert.equal(receipt.registered.length, 1); assert.equal(receipt.registrationOutcomeUncertain, true); assert.equal(f.commands.some(entry => ['run-task', 'update-service', 'deregister-task-definition'].includes(entry.args[1])), false); } finally { f.clean(); } });
test('anchor source and registered exact environment permutations remain accepted', async () => { const f = anchorFixture(); try { const plan = await createAnchor128Plan(f.input, f.options); f.behavior.anchorSourceMutation = value => value.taskDefinition.containerDefinitions[0].environment.reverse(); f.behavior.registeredMutation = value => value.taskDefinition.containerDefinitions[0].environment.reverse(); const result = await registerAnchor128Inactive(plan, f.authorization(plan), f.options); assert.equal(result.registered.length, 2); } finally { f.clean(); } });
test('anchor registered duplicate changed missing environment and ordered tags commands reject', async () => { for (const change of [value => { const entries = value.taskDefinition.containerDefinitions[0].environment; entries.push(structuredClone(entries[0])); }, value => { value.taskDefinition.containerDefinitions[0].environment.find(entry => entry.name === 'UNRELATED_VALUE').value = 'changed'; }, value => { value.taskDefinition.containerDefinitions[0].environment.pop(); }, value => { value.taskDefinition.containerDefinitions[0].command.reverse(); }, value => { value.tags.push({ key: 'unexpected', value: 'changed' }); }]) { const f = anchorFixture(); try { const plan = await createAnchor128Plan(f.input, f.options); f.behavior.registeredMutation = change; await assert.rejects(registerAnchor128Inactive(plan, f.authorization(plan), f.options), /COMPATIBLE_ANCHOR128_REGISTRATION_FAILED/); assert.equal(JSON.parse(readFileSync(path.join(f.input.outputDirectory, 'registration.private.json'))).registered.length, 1); } finally { f.clean(); } } });
test('anchor remote config drift and generated request drift fail without registration', async () => { for (const change of ['remote', 'request']) { const f = anchorFixture(); try { const plan = await createAnchor128Plan(f.input, f.options); if (change === 'remote') f.options.verifyRegistry = async () => ({ digest: sourceImage, configDigest: FALLBACK.config, platformDigest: FALLBACK.platform }); else { const p = JSON.parse(readFileSync(plan.path)); writeFileSync(p.generated.api.path, '{}'); } await assert.rejects(registerAnchor128Inactive(plan, f.authorization(plan), f.options)); assert.equal(f.commands.some(entry => entry.args[1] === 'register-task-definition'), false); } finally { f.clean(); } } });
test('anchor post-registration service drift records failure without rollback or deregistration', async () => { const f = anchorFixture(); try { const plan = await createAnchor128Plan(f.input, f.options); f.behavior.afterServicesChanged = true; await assert.rejects(registerAnchor128Inactive(plan, f.authorization(plan), f.options), /COMPATIBLE_ANCHOR128_REGISTRATION_FAILED/); const receipt = JSON.parse(readFileSync(path.join(f.input.outputDirectory, 'registration.private.json'))); assert.equal(receipt.registered.length, 2); assert.equal(receipt.status, 'failed_retained_inactive'); assert.equal(f.commands.some(entry => ['update-service', 'deregister-task-definition'].includes(entry.args[1])), false); } finally { f.clean(); } });

// Source admission is a set; rendering must retain its original CSV bytes.
test('production121 serialization order is accepted and preserved in unused image clones', () => {
  const sources = Object.fromEntries(['api', 'scheduler-worker'].map(role => {
    const value = definition(role, 128);
    setEnv(value, 'RLS_ENABLED_TABLES', observedAdmissionOrder().join(','));
    value.taskDefinition.containerDefinitions.push({ name: 'synthetic-sidecar', image: 'preserved-sidecar', essential: false, environment: [{ name: 'UNRELATED', value: 'unchanged' }] });
    return [role, value];
  }));
  const before = structuredClone(sources);
  const live = { failures: [], services: Object.entries(sources).map(([role, value]) => ({ serviceName: `schoolpilot-production-${role}`, taskDefinition: value.taskDefinition.taskDefinitionArn, status: 'ACTIVE', desiredCount: 1, runningCount: 1, pendingCount: 0, deployments: [{ status: 'PRIMARY', rolloutState: 'COMPLETED' }] })) };
  const targetSource = 'a'.repeat(40);
  const requests = renderUnused121Pair(sources, live, targetSource, targetImage);
  assert.deepEqual(sources, before);
  for (const role of ['api', 'scheduler-worker']) {
    const { taskDefinitionArn, revision, status, registeredAt, registeredBy, ...expected } = structuredClone(sources[role].taskDefinition);
    expected.tags = structuredClone(sources[role].tags);
    expected.containerDefinitions[0].image = `135775632425.dkr.ecr.us-east-1.amazonaws.com/schoolpilot-production-api@${targetImage}`;
    expected.containerDefinitions[0].environment.find(entry => entry.name === 'GIT_SHA').value = targetSource;
    assert.deepEqual(requests[role], expected);
    assert.equal(requests[role].containerDefinitions[0].environment.find(entry => entry.name === 'RLS_ENABLED_TABLES').value, observedAdmissionOrder().join(','));
  }
});
test('anchor128 appends reviewed bundles without rewriting production121 serialization', () => {
  const sources = Object.fromEntries(['api', 'scheduler-worker'].map(role => {
    const value = definition(role, 128); setEnv(value, 'RLS_ENABLED_TABLES', observedAdmissionOrder().join(',')); return [role, value];
  }));
  const before = structuredClone(sources);
  const requests = renderAnchor128Pair(sources, FALLBACK.application, sourceImage);
  assert.deepEqual(sources, before);
  const expected = [...observedAdmissionOrder(), ...inventoryFor(128).slice(121)].join(',');
  for (const role of ['api', 'scheduler-worker']) {
    assert.equal(requests[role].containerDefinitions[0].environment.find(entry => entry.name === 'RLS_ENABLED_TABLES').value, expected);
    assertOnlyAnchorAdmissionChanged(sources[role], requests[role], role, FALLBACK.application, sourceImage);
  }
  assert.deepEqual(anchor128Stages()[0], inventoryFor(128).slice(0, 121));
});
test('fallback128 and129 preserve permuted admission and every unrelated field', () => {
  for (const count of [128, 129]) for (const role of ['api', 'scheduler-worker']) {
    const value = definition(role, count), raw = observedAdmissionOrder(inventoryFor(count)).join(',');
    setEnv(value, 'RLS_ENABLED_TABLES', raw); const before = structuredClone(value);
    const request = renderRequest(value, role, FALLBACK.application, sourceImage, targetImage, count);
    stamp(request, role); assertOnlyImageIdentityChanged(value, request, role, targetImage);
    assert.equal(request.containerDefinitions[0].environment.find(entry => entry.name === 'RLS_ENABLED_TABLES').value, raw);
    assert.deepEqual(value, before);
  }
});
test('source admission rejects missing extra changed and duplicate table membership', () => {
  const canonical = anchor128Stages()[0];
  const changed = [...canonical]; changed[72] = 'unreviewed_extra_table';
  const duplicate = [...canonical]; duplicate[72] = duplicate[74];
  for (const tables of [canonical.slice(0, -1), [...canonical, 'unreviewed_extra_table'], changed, duplicate]) {
    const value = definition('api', 128); setEnv(value, 'RLS_ENABLED_TABLES', tables.join(','));
    assert.throws(() => validateSourceResponse(value, 'api', FALLBACK.application, sourceImage, canonical), /ADMISSION_DRIFT/);
  }
});
test('source admission rejects empty malformed and whitespace CSV names', () => {
  const canonical = anchor128Stages()[0];
  for (const raw of [undefined, '', `${canonical.join(',')},`, canonical.map((name, index) => index === 72 ? 'Bad-Table' : name).join(','), canonical.map((name, index) => index === 72 ? ` ${name}` : name).join(',')]) {
    const value = definition('api', 128); setEnv(value, 'RLS_ENABLED_TABLES', raw);
    assert.throws(() => validateSourceResponse(value, 'api', FALLBACK.application, sourceImage, canonical), /ADMISSION_DRIFT/);
  }
});
test('source admission rejects empty duplicate or malformed expected inventories', () => {
  const value = definition('api', 128), expected = inventoryFor(128);
  for (const inventory of [[], [...expected.slice(0, -1), expected[0]], expected.map((name, index) => index === 0 ? '' : name)]) {
    assert.throws(() => validateSourceResponse(value, 'api', FALLBACK.application, sourceImage, inventory), /ADMISSION_DRIFT/);
  }
});
