import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { hash, REGISTRY, planPublication, publishImage, planUnused121, registerUnused121, renderUnused121Pair, validateLocalScan, validateMainCi, validatePublicationPlatform } from '../scripts/prepare-release-artifacts.mjs';
import { anchor128Stages, FALLBACK } from '../scripts/register-compatible-fallback-inactive.mjs';
import { SCANNER } from '../scripts/verify-legacy-deploy-image.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = 'c'.repeat(40), imageId = `sha256:${'a'.repeat(64)}`, baselineImage = `sha256:${'b'.repeat(64)}`;
const uri = `${REGISTRY.account}.dkr.ecr.${REGISTRY.region}.amazonaws.com/${REGISTRY.repository}`;
const now = Date.parse('2026-10-04T22:00:00Z');
function tar(entries) {
  const output = [];
  for (const [name, value] of Object.entries(entries)) { const bytes = Buffer.from(value), header = Buffer.alloc(512); header.write(name); header.write(bytes.length.toString(8).padStart(11, '0') + '\0', 124); header[156] = 48; output.push(header, bytes, Buffer.alloc((512 - bytes.length % 512) % 512)); }
  return Buffer.concat([...output, Buffer.alloc(1024)]);
}
function definition(role) {
  const family = role === 'api' ? 'schoolpilot-production-api-emergency' : 'schoolpilot-production-scheduler-worker';
  return { taskDefinition: { taskDefinitionArn: `arn:aws:ecs:${REGISTRY.region}:${REGISTRY.account}:task-definition/${family}:100`, revision: 100, family, status: 'ACTIVE', networkMode: 'awsvpc', requiresCompatibilities: ['FARGATE'], cpu: role === 'api' ? '1024' : '512', memory: role === 'api' ? '2048' : '1024', taskRoleArn: 'synthetic-task-role', executionRoleArn: 'synthetic-execution-role', runtimePlatform: { cpuArchitecture: 'X86_64', operatingSystemFamily: 'LINUX' }, volumes: [], containerDefinitions: [{ name: role, image: `${uri}@${baselineImage}`, essential: true, command: ['node', role === 'api' ? 'dist/index.js' : 'dist/worker.js'], secrets: [{ name: 'DATABASE_URL', valueFrom: 'synthetic-secret-reference' }], environment: Object.entries({ GIT_SHA: '7'.repeat(40), SERVICE_NAME: role, RLS_GUC_ENABLED: 'true', RLS_ENABLED_TABLES: anchor128Stages()[0].join(','), CLASSPILOT_USAGE_ROLLUP_MODE: 'off', CLASSPILOT_DIGITAL_USAGE_MODE: 'off', CLASSPILOT_CAP_PRECISE_RESTRICTION_RESOURCES_V1: 'false', CLASSPILOT_CAP_FOCUS_TAB_V1: 'false', CLASSPILOT_CAP_PRIVATE_CHAT_LIFECYCLE_V1: 'false', CLASSPILOT_CAPABILITY_ROLLOUTS_JSON: '{}', DB_POOL_MAX: '20', SESSION_DB_POOL_MAX: '2', SCHEDULER_DB_POOL_MAX: '5', UNRELATED: 'unchanged' }).map(([name, value]) => ({ name, value })) }] }, tags: [{ key: 'Project', value: 'SchoolPilot' }] };
}
function fixture() {
  const directory = mkdtempSync(path.join(os.tmpdir(), 'sp-artifact-only-')), inputs = path.join(directory, 'inputs'); mkdirSync(inputs);
  const pin = (name, value, raw) => { const filename = path.join(inputs, name); writeFileSync(filename, raw ?? JSON.stringify(value)); return { path: filename, sha256: hash(readFileSync(filename)) }; };
  const scanDirectory = path.join(inputs, 'scan'); mkdirSync(scanDirectory); mkdirSync(path.join(scanDirectory, 'input')); mkdirSync(path.join(scanDirectory, 'reports'));
  const configBytes = JSON.stringify({ os: 'linux', architecture: 'amd64', config: { Labels: { 'org.opencontainers.image.revision': source } } }), configDigest = `sha256:${hash(configBytes)}`;
  const archive = tar({ 'manifest.json': JSON.stringify([{ Config: `${hash(configBytes)}.json` }]), [`${hash(configBytes)}.json`]: configBytes });
  writeFileSync(path.join(scanDirectory, 'input/image.tar'), archive);
  const report = { SchemaVersion: 2, ArtifactType: 'container_image', Metadata: { ImageID: configDigest }, Results: [{ Target: 'synthetic', Vulnerabilities: [] }] }; writeFileSync(path.join(scanDirectory, 'reports/trivy.json'), JSON.stringify(report));
  writeFileSync(path.join(scanDirectory, 'cleanup.json'), JSON.stringify({ complete: true, ownedScanner: 'schoolpilot-image-scan-1234' }));
  const scan = { schemaVersion: 1, sourceSha: source, passed: true, scanner: SCANNER, os: 'linux', architecture: 'amd64', imageId, configDigest, dockerHost: 'synthetic-docker-host', reportSha256: hash(JSON.stringify(report)), archiveSha256: hash(archive), counts: { UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0 } };
  const scanPath = path.join(scanDirectory, 'scan-receipt.json'); writeFileSync(scanPath, JSON.stringify(scan)); const scanPin = { path: scanPath, sha256: hash(readFileSync(scanPath)) };
  const ci = { repository: 'bzinkan/SchoolPilot', branch: 'main', source, runs: [{ workflowName: 'CI', status: 'completed', conclusion: 'success', event: 'push', headBranch: 'main', headSha: source }] };
  const repo = { repositories: [{ registryId: REGISTRY.account, repositoryName: REGISTRY.repository, imageTagMutability: 'MUTABLE', imageTagMutabilityExclusionFilters: null }] };
  const input = { schemaVersion: 1, kind: 'serving-anchor', source, sourceDirectory: path.join(directory, 'source'), outputDirectory: path.join(directory, 'publication'), scan: scanPin, scanCleanup: pin('scan-custody.json', { schemaVersion: 1, complete: true, forced: false, exactOwned: true, scannerExitCode: 0, ownedScannerAbsent: true, ownedScanner: 'schoolpilot-image-scan-1234', scanSha256: scanPin.sha256 }), mainCi: pin('main-ci.json', ci), repository: pin('repository.json', repo), publisherConfiguration: pin('publisher.json', { repository: 'bzinkan/SchoolPilot', variable: 'IMMUTABLE_RELEASE_IMAGE_ENABLED', enabled: false }) };
  const sources = { api: definition('api'), 'scheduler-worker': definition('scheduler-worker') };
  const services = { services: roles().map(role => ({ serviceName: `schoolpilot-production-${role === 'api' ? 'api' : 'scheduler-worker'}`, status: 'ACTIVE', taskDefinition: sources[role].taskDefinition.taskDefinitionArn, desiredCount: 1, runningCount: 1, pendingCount: 0, deployments: [{ status: 'PRIMARY', rolloutState: 'COMPLETED', taskDefinition: sources[role].taskDefinition.taskDefinitionArn }] })), failures: [] };
  const manifestType = 'application/vnd.oci.image.manifest.v1+json', manifest = JSON.stringify({ schemaVersion: 2, mediaType: manifestType, config: { digest: configDigest }, layers: [] }), registryDigest = `sha256:${hash(manifest)}`;
  const tags = new Map(), registered = new Map(), commands = [], behavior = { clock: now };
  const image = (tag, value = registryDigest, body = manifest) => ({ registryId: REGISTRY.account, repositoryName: REGISTRY.repository, imageId: { imageTag: tag, imageDigest: value }, imageManifest: body, imageManifestMediaType: manifestType });
  let serviceReads = 0;
  const run = async (executable, args) => {
    commands.push({ executable, args }); const ok = value => ({ code: 0, stdout: typeof value === 'string' ? value : JSON.stringify(value), stderr: '' });
    if (executable === 'git') { const operation = args[2]; if (operation === 'rev-parse') return ok(args[1] === root ? 'caacdf5f15b2044420c27dedab90e93848d712a6' : behavior.sourceMoved ? 'd'.repeat(40) : source); if (operation === 'status') return ok(behavior.dirty ? ' M synthetic' : ''); if (operation === 'diff') return ok(behavior.applicationChanged ? 'src/app.ts' : ''); }
    if (executable === 'pwsh') return ok('');
    if (executable === 'gh') { if (args.includes('repos/bzinkan/SchoolPilot/branches/main')) return ok({ commit: { sha: behavior.mainMoved ? 'd'.repeat(40) : source } }); if (args.includes('repos/bzinkan/SchoolPilot/actions/variables?per_page=100')) return ok([{ variables: [] }, { variables: behavior.publisherEnabled ? [{ name: 'IMMUTABLE_RELEASE_IMAGE_ENABLED', value: 'true' }] : [] }]); return ok(behavior.ciFailed ? [{ ...ci.runs[0], conclusion: 'failure' }] : ci.runs); }
    if (executable === 'docker') { const operation = args[2]; if (operation === 'image') return ok([{ Id: imageId, Os: 'linux', Architecture: 'amd64', Config: { Labels: { 'org.opencontainers.image.revision': source } } }]); if (operation === 'push') { if (behavior.pushFailure) return { code: 1, stdout: '', stderr: 'synthetic failed push' }; tags.set(source, image(source)); return ok('synthetic push'); } if (operation === 'tag') return ok(''); }
    if (executable === 'aws') {
      const operation = args[1];
      if (operation === 'get-caller-identity') return ok({ Account: behavior.wrongAccount ? '000000000000' : REGISTRY.account });
      if (operation === 'describe-repositories') return ok(behavior.policyChanged ? { repositories: [{ ...repo.repositories[0], imageTagMutability: 'IMMUTABLE' }] } : repo);
      if (operation === 'get-login-password') return ok('synthetic-secret');
      if (operation === 'batch-get-image') { const id = args[args.indexOf('--image-ids') + 1]; if (id.startsWith('imageTag=')) { const tag = id.slice(9); return ok(tags.has(tag) ? { images: [tags.get(tag)], failures: [] } : { images: [], failures: [{ failureCode: 'ImageNotFound' }] }); } const value = [...tags.values()].find(value => value.imageId.imageDigest === id.slice(12)); return ok(value ? { images: [value], failures: [] } : { images: [], failures: [{ failureCode: 'ImageNotFound' }] }); }
      if (operation === 'put-image') { const tag = args[args.indexOf('--image-tag') + 1]; tags.set(tag, image(tag)); return ok({ image: image(tag) }); }
      if (operation === 'describe-services') { serviceReads++; const value = structuredClone(services); if (behavior.servicesChanged && serviceReads > 1) value.services[0].desiredCount = 2; return ok(value); }
      if (operation === 'describe-task-definition') { const arn = args[args.indexOf('--task-definition') + 1], role = arn.includes('scheduler-worker') ? 'scheduler-worker' : 'api'; const value = structuredClone(registered.get(arn) ?? sources[role]); if (behavior.sourceDrift && !registered.has(arn)) value.tags.push({ key: 'changed', value: 'changed' }); if (behavior.registeredDrift && registered.has(arn)) value.taskDefinition.containerDefinitions[0].environment.find(value => value.name === 'DB_POOL_MAX').value = '32'; return ok(value); }
      if (operation === 'register-task-definition') { const filename = args[args.indexOf('--cli-input-json') + 1].replace(/^file:\/\//, ''), request = JSON.parse(readFileSync(filename)); const { tags: requestTags, ...task } = request; const role = task.containerDefinitions[0].name; if (behavior.failWorker && role === 'scheduler-worker') return { code: 1, stdout: '', stderr: 'synthetic transport failure' }; const arn = `arn:aws:ecs:${REGISTRY.region}:${REGISTRY.account}:task-definition/${task.family}:201`; const response = { taskDefinition: { ...task, status: 'ACTIVE', revision: 201, taskDefinitionArn: arn }, tags: requestTags }; registered.set(arn, response); if (behavior.expireAfterRegistration) behavior.clock = now + 1_200_000; return ok(response); }
    }
    throw new Error(`Unexpected mock command ${executable}:${args[1]}`);
  };
  const options = { run, now: () => behavior.clock, login: async () => { commands.push({ executable: 'stdin-login', args: [] }); } };
  const authorization = (plan, operation) => { const window = pin(`${operation}-window.json`, { owner: 'release-artifact-preparation', operation, source, planSha256: plan.sha256, startsAtUtc: new Date(now - 1000).toISOString(), expiresAtUtc: new Date(now + 1_199_000).toISOString(), servicesMayChange: false, tasksMayLaunch: false, productionDatabaseOperations: 0, singlePublisher: true }); return pin(`${operation}-auth.json`, { schemaVersion: 1, authorized: true, operation, planSha256: plan.sha256, singlePublisher: true, window }); };
  const registrationInput = publication => ({ ...input, outputDirectory: path.join(directory, 'registration'), publication, api: pin('api.json', sources.api), worker: pin('worker.json', sources['scheduler-worker']), liveServices: pin('services.json', services) });
  return { directory, input, scan, configDigest, registryDigest, ci, sources, services, commands, behavior, options, pin, tags, image, authorization, registrationInput, clean: () => rmSync(directory, { recursive: true, force: true }) };
}
const roles = () => ['api', 'scheduler-worker'];
const mutateEnv = (definition, name, value) => { definition.taskDefinition.containerDefinitions[0].environment.find(entry => entry.name === name).value = value; };
async function published(f) { const plan = await planPublication(f.input, f.options); return publishImage(plan, f.authorization(plan, 'PublishImage'), f.options); }
function noOperationalCommands(f) { assert.equal(f.commands.some(value => value.executable === 'aws' && ['run-task', 'update-service', 'register-scalable-target', 'deregister-task-definition', 'put-image-tag-mutability', 'delete-image'].includes(value.args[1])), false); }

test('offline publication Plan binds actual saved config and scan without AWS Docker or GH', async () => { const f = fixture(); try { const result = await planPublication(f.input, f.options), plan = JSON.parse(readFileSync(result.path)); assert.equal(plan.cloudMutationsDuringPlan, 0); assert.equal(plan.signed, false); assert.deepEqual(plan.tags, [source, source.slice(0, 12)]); assert.equal(f.commands.some(value => ['aws', 'docker', 'gh'].includes(value.executable)), false); } finally { f.clean(); } });
test('dirty moved or application-different source rejects offline Plan', async () => { for (const key of ['dirty', 'sourceMoved', 'applicationChanged']) { const f = fixture(); try { f.behavior[key] = true; await assert.rejects(planPublication(f.input, f.options)); assert.equal(f.commands.some(value => value.executable === 'aws'), false); } finally { f.clean(); } } });
test('main CI rejects PR event wrong source non-green and missing CI', () => { const f = fixture(); try { for (const change of [proof => { proof.runs[0].event = 'pull_request'; }, proof => { proof.runs[0].headSha = 'd'.repeat(40); }, proof => { proof.runs[0].conclusion = 'failure'; }, proof => { proof.runs[0].workflowName = 'Other'; }]) { const copy = structuredClone(f.ci); change(copy); assert.throws(() => validateMainCi(copy, source)); } } finally { f.clean(); } });
test('tampered archive report or forced scanner cleanup rejects actual local scan', async () => { for (const change of ['archive', 'report', 'cleanup']) { const f = fixture(); try { if (change === 'archive') writeFileSync(path.join(path.dirname(f.input.scan.path), 'input/image.tar'), 'tampered'); else if (change === 'report') writeFileSync(path.join(path.dirname(f.input.scan.path), 'reports/trivy.json'), '{}'); else f.input.scanCleanup = f.pin('forced.json', { ...JSON.parse(readFileSync(f.input.scanCleanup.path)), forced: true }); await assert.rejects(validateLocalScan(f.input)); } finally { f.clean(); } } });
test('publication uses actual mutable repository unchanged with explicit single publisher and no latest', async () => { const f = fixture(); try { const result = await published(f), receipt = JSON.parse(readFileSync(result.path)); assert.equal(receipt.status, 'published'); assert.equal(receipt.signed, false); assert.equal(receipt.atomicTagExclusionGuaranteed, false); assert.equal(receipt.registryDigest, f.registryDigest); assert.deepEqual([...f.tags.keys()].sort(), [source, source.slice(0, 12)].sort()); assert.equal(f.commands.some(value => value.args.some(arg => arg.includes(':latest'))), false); noOperationalCommands(f); } finally { f.clean(); } });
test('publication rejects wrong operation unapproved authorization and expired window before commands', async () => { for (const change of ['operation', 'authorized', 'singlePublisher', 'expired']) { const f = fixture(); try { const plan = await planPublication(f.input, f.options), auth = f.authorization(plan, 'PublishImage'), value = JSON.parse(readFileSync(auth.path)); if (change === 'expired') f.behavior.clock = now + 1_200_000; else value[change] = change === 'operation' ? 'RegisterUnused121' : false; const changed = f.pin('changed-auth.json', value); const start = f.commands.length; await assert.rejects(publishImage(plan, changed, f.options)); assert.equal(f.commands.slice(start).some(value => ['aws', 'docker'].includes(value.executable)), false); } finally { f.clean(); } } });
test('fresh account main CI publisher and repository drift block any push', async () => { for (const key of ['wrongAccount', 'mainMoved', 'ciFailed', 'publisherEnabled', 'policyChanged']) { const f = fixture(); try { const plan = await planPublication(f.input, f.options); f.behavior[key] = true; await assert.rejects(publishImage(plan, f.authorization(plan, 'PublishImage'), f.options)); assert.equal(f.commands.some(value => value.executable === 'docker' && value.args[2] === 'push'), false); } finally { f.clean(); } } });
test('existing conflicting source-tag config fails without overwriting or deleting', async () => { const f = fixture(); try { const other = JSON.stringify({ schemaVersion: 2, mediaType: 'application/vnd.oci.image.manifest.v1+json', config: { digest: `sha256:${'9'.repeat(64)}` }, layers: [] }); f.tags.set(source.slice(0, 12), f.image(source.slice(0, 12), `sha256:${hash(other)}`, other)); const plan = await planPublication(f.input, f.options); await assert.rejects(publishImage(plan, f.authorization(plan, 'PublishImage'), f.options)); assert.equal(f.commands.some(value => value.executable === 'docker' && value.args[2] === 'push' || value.executable === 'aws' && value.args[1] === 'put-image'), false); noOperationalCommands(f); } finally { f.clean(); } });
test('exact existing publication is reused and only absent source alias is created', async () => { const f = fixture(); try { f.tags.set(source.slice(0, 12), f.image(source.slice(0, 12))); const result = await published(f); assert.equal(JSON.parse(readFileSync(result.path)).status, 'published'); assert.equal(f.commands.some(value => value.executable === 'docker' && value.args[2] === 'push'), false); assert.equal(f.commands.filter(value => value.executable === 'aws' && value.args[1] === 'put-image').length, 1); } finally { f.clean(); } });
test('failed push persists uncertainty and cannot automatically repeat the plan', async () => { const f = fixture(); try { const plan = await planPublication(f.input, f.options), auth = f.authorization(plan, 'PublishImage'); f.behavior.pushFailure = true; await assert.rejects(publishImage(plan, auth, f.options)); const receipt = JSON.parse(readFileSync(path.join(f.input.outputDirectory, 'publication.private.json'))); assert.equal(receipt.status, 'failed_publication_retained'); assert.equal(receipt.publicationOutcomeUncertain, true); await assert.rejects(publishImage(plan, auth, f.options), /PLAN_ALREADY_USED/); assert.equal(f.commands.filter(value => value.executable === 'docker' && value.args[2] === 'push').length, 1); } finally { f.clean(); } });
test('unused121 rendering changes only image and GIT_SHA while preserving live resources and secret refs', () => { const f = fixture(); try { const requests = renderUnused121Pair(f.sources, f.services, source, f.registryDigest); for (const role of roles()) { const before = f.sources[role].taskDefinition, after = requests[role]; assert.deepEqual([after.cpu, after.memory, after.containerDefinitions[0].secrets, after.containerDefinitions[0].command], [before.cpu, before.memory, before.containerDefinitions[0].secrets, before.containerDefinitions[0].command]); assert.equal(after.containerDefinitions[0].environment.find(value => value.name === 'RLS_ENABLED_TABLES').value.split(',').length, 121); } } finally { f.clean(); } });
test('unused121 rejects wrong admission Usage capability resources or a non-serving source', () => { for (const change of [value => mutateEnv(value, 'RLS_ENABLED_TABLES', anchor128Stages()[1].join(',')), value => mutateEnv(value, 'CLASSPILOT_USAGE_ROLLUP_MODE', 'on'), value => mutateEnv(value, 'CLASSPILOT_CAP_PRIVATE_CHAT_LIFECYCLE_V1', 'true'), value => { value.taskDefinition.memory = '4096'; }, value => { value.taskDefinition.taskDefinitionArn = value.taskDefinition.taskDefinitionArn.replace(':100', ':101'); }]) { const f = fixture(); try { change(f.sources.api); assert.throws(() => renderUnused121Pair(f.sources, f.services, source, f.registryDigest)); } finally { f.clean(); } } });
test('registration Plan requires successful publication and creates only exact private unused requests', async () => { const f = fixture(); try { const publication = await published(f), input = f.registrationInput(publication), start = f.commands.length, result = await planUnused121(input, f.options); const plan = JSON.parse(readFileSync(result.path)); assert.equal(plan.operation, 'RegisterUnused121'); assert.equal(Object.keys(plan.generated).length, 2); assert.equal(f.commands.slice(start).some(value => ['aws', 'docker', 'gh'].includes(value.executable)), false); const failed = f.pin('failed-publication.json', { ...JSON.parse(readFileSync(publication.path)), status: 'failed_publication_retained' }); await assert.rejects(planUnused121({ ...input, publication: failed, outputDirectory: path.join(f.directory, 'bad-registration') }, f.options)); } finally { f.clean(); } });
test('registration returns two unused121 ARNs and leaves services untouched without tasks or SQL', async () => { const f = fixture(); try { const publication = await published(f), plan = await planUnused121(f.registrationInput(publication), f.options), result = await registerUnused121(plan, f.authorization(plan, 'RegisterUnused121'), f.options), receipt = JSON.parse(readFileSync(result.path)); assert.equal(receipt.status, 'registered_unused121'); assert.equal(receipt.registered.length, 2); assert.equal(receipt.servicesUnchanged, true); noOperationalCommands(f); assert.equal(f.commands.filter(value => value.executable === 'aws' && value.args[1] === 'register-task-definition').length, 2); } finally { f.clean(); } });
test('registration rejects publication authorization and generated request tamper without registration', async () => { for (const change of ['authorization', 'request']) { const f = fixture(); try { const publication = await published(f), plan = await planUnused121(f.registrationInput(publication), f.options), auth = f.authorization(plan, 'RegisterUnused121'); if (change === 'request') writeFileSync(JSON.parse(readFileSync(plan.path)).generated.api.path, '{}'); const changed = change === 'authorization' ? f.pin('wrong-registration-auth.json', { ...JSON.parse(readFileSync(auth.path)), operation: 'PublishImage' }) : auth; await assert.rejects(registerUnused121(plan, changed, f.options)); assert.equal(f.commands.some(value => value.executable === 'aws' && value.args[1] === 'register-task-definition'), false); } finally { f.clean(); } } });
test('live definition drift fails before register and registered drift retains returned ARN', async () => { for (const key of ['sourceDrift', 'registeredDrift']) { const f = fixture(); try { const publication = await published(f), plan = await planUnused121(f.registrationInput(publication), f.options); f.behavior[key] = true; await assert.rejects(registerUnused121(plan, f.authorization(plan, 'RegisterUnused121'), f.options)); const receipt = JSON.parse(readFileSync(path.join(f.directory, 'registration/registration.private.json'))); assert.equal(receipt.registered.length, key === 'sourceDrift' ? 0 : 1); noOperationalCommands(f); } finally { f.clean(); } } });
test('partial worker transport failure persists first ARN and uncertain worker without cloud cleanup', async () => { const f = fixture(); try { const publication = await published(f), plan = await planUnused121(f.registrationInput(publication), f.options); f.behavior.failWorker = true; await assert.rejects(registerUnused121(plan, f.authorization(plan, 'RegisterUnused121'), f.options)); const receipt = JSON.parse(readFileSync(path.join(f.directory, 'registration/registration.private.json'))); assert.equal(receipt.registered.length, 1); assert.equal(receipt.lastAttemptedRole, 'scheduler-worker'); assert.equal(receipt.registrationOutcomeUncertain, true); noOperationalCommands(f); } finally { f.clean(); } });
test('post-register window expiry retains returned ARN immediately before rejecting', async () => { const f = fixture(); try { const publication = await published(f), plan = await planUnused121(f.registrationInput(publication), f.options); f.behavior.expireAfterRegistration = true; await assert.rejects(registerUnused121(plan, f.authorization(plan, 'RegisterUnused121'), f.options)); const receipt = JSON.parse(readFileSync(path.join(f.directory, 'registration/registration.private.json'))); assert.equal(receipt.registered.length, 1); assert.equal(receipt.registrationOutcomeUncertain, false); assert.ok(readFileSync(path.join(f.directory, 'registration/api.register-response.private.json')).includes(Buffer.from(receipt.registered[0].arn))); } finally { f.clean(); } });
test('post-registration service drift stays failed with both ARNs retained and no rollback', async () => { const f = fixture(); try { const publication = await published(f), plan = await planUnused121(f.registrationInput(publication), f.options); f.behavior.servicesChanged = true; await assert.rejects(registerUnused121(plan, f.authorization(plan, 'RegisterUnused121'), f.options)); const receipt = JSON.parse(readFileSync(path.join(f.directory, 'registration/registration.private.json'))); assert.equal(receipt.registered.length, 2); assert.equal(receipt.status, 'failed_registration_retained'); noOperationalCommands(f); } finally { f.clean(); } });
test('fallback publication remains exact C578 and cannot create serving anchors', async () => { const f = fixture(); try { const wrong = { ...f.input, kind: 'fallback', source: source }; await assert.rejects(planPublication(wrong, f.options), /EXACT_FALLBACK_IMAGE_REQUIRED/); await assert.rejects(planUnused121({ ...f.input, kind: 'fallback', source: FALLBACK.source }, f.options), /ANCHOR_PUBLICATION_ONLY/); } finally { f.clean(); } });
test('legacy scan cleanup owner mismatch and post-plan cleanup-byte change reject', async () => { const f = fixture(); try { const filename = path.join(path.dirname(f.input.scan.path), 'cleanup.json'); writeFileSync(filename, JSON.stringify({ complete: true, ownedScanner: 'schoolpilot-image-scan-other' })); await assert.rejects(planPublication(f.input, f.options), /SCAN_CLEANUP_UNCONFIRMED/); writeFileSync(filename, JSON.stringify({ complete: true, ownedScanner: 'schoolpilot-image-scan-1234' })); const plan = await planPublication(f.input, f.options); writeFileSync(filename, JSON.stringify({ complete: true, ownedScanner: 'schoolpilot-image-scan-1234', changed: true })); const start = f.commands.length; await assert.rejects(publishImage(plan, f.authorization(plan, 'PublishImage'), f.options), /INPUT_CHANGED/); assert.equal(f.commands.slice(start).some(value => ['aws', 'docker'].includes(value.executable)), false); } finally { f.clean(); } });
test('source alias appearing between inspection and mutation stops publication', async () => { const f = fixture(); try { const plan = await planPublication(f.input, f.options); let tagReads = 0; const run = async (exe, args, options) => { if (exe === 'aws' && args[1] === 'batch-get-image' && args.includes(`imageTag=${source.slice(0, 12)}`)) { tagReads++; if (tagReads === 2) f.tags.set(source.slice(0, 12), f.image(source.slice(0, 12))); } return f.options.run(exe, args, options); }; await assert.rejects(publishImage(plan, f.authorization(plan, 'PublishImage'), { ...f.options, run })); assert.equal(f.commands.some(value => value.executable === 'docker' && value.args[2] === 'push'), false); } finally { f.clean(); } });
test('source and archive labels must bind exact linux amd64 scanned config', async () => { const f = fixture(); try { const changed = { ...f.scan, architecture: 'arm64' }; f.input.scan = f.pin('wrong-platform.json', changed); await assert.rejects(planPublication(f.input, f.options), /SCAN_IDENTITY_INVALID/); } finally { f.clean(); } });
test('C578 publication binds its exact platform and existing registry proofs remain immutable', async () => { const proof = { digest: `sha256:${'e'.repeat(64)}`, platformDigest: FALLBACK.platform, configDigest: FALLBACK.config }; validatePublicationPlatform('fallback', proof, FALLBACK.config); assert.throws(() => validatePublicationPlatform('fallback', { ...proof, platformDigest: `sha256:${'d'.repeat(64)}` }, FALLBACK.config), /EXACT_FALLBACK_PLATFORM_REQUIRED/); const f = fixture(); try { const filename = path.join(path.dirname(f.input.scan.path), 'registry-proof.json'), bytes = 'retained prior proof'; writeFileSync(filename, bytes); await assert.rejects(planPublication(f.input, f.options), /FRESH_REGISTRY_PROOF_REQUIRED/); assert.equal(readFileSync(filename, 'utf8'), bytes); assert.equal(f.commands.length, 0); } finally { f.clean(); } });
