import test from 'node:test';
import assert from 'node:assert/strict';
import {numericalRunChecks} from './numerical-checks.mjs';
const workers=()=>[0,1].map(schoolIndex=>({schoolIndex,correct:true,durationMs:48000}));
function minimal(){return {phases:[{name:'combined',workers:workers()}],correctness:{currentDayWorkers:workers()},poolReadiness:['api','session','worker'].map(name=>({name,max:{api:16,session:2,worker:5}[name],acquisitionCalls:1,queryCalls:1,sameRole:true,databaseSuperuser:false,databaseBypassRls:false,neutralSchool:true,applicationSuperScope:name==='worker',checkoutDeadlineMs:name==='worker'?10000:5000,statementDeadlineMs:name==='worker'?60000:15000}))};}
test('strict worker proof needs one whole operation from each expected school, including queue',()=>{const m=minimal();assert.equal(numericalRunChecks(m,'diagnostic').distinctWholeWorkers,true);m.phases[0].workers[1].schoolIndex=0;assert.equal(numericalRunChecks(m,'diagnostic').distinctWholeWorkers,false);m.phases[0].workers=workers();m.phases[0].workers[1].durationMs=48000.01;assert.equal(numericalRunChecks(m,'diagnostic').distinctWholeWorkers,false);});
test('current-day workers cannot substitute duplicate school results',()=>{const m=minimal();assert.equal(numericalRunChecks(m,'diagnostic').distinctCurrentDayWorkers,true);m.correctness.currentDayWorkers[1].schoolIndex=0;assert.equal(numericalRunChecks(m,'diagnostic').distinctCurrentDayWorkers,false);});
test('pool proof is tied to all three actual restricted pools and unchanged budgets',()=>{const m=minimal();assert.equal(numericalRunChecks(m,'diagnostic').actualRestrictedPools,true);for(const change of [p=>p.pop(),p=>p[0].databaseSuperuser=true,p=>p[1].databaseBypassRls=true,p=>p[2].acquisitionCalls=2,p=>p[2].statementDeadlineMs=61000,p=>p[0].checkoutDeadlineMs=6000,p=>p[0].max=17,p=>p[0].applicationSuperScope=true]){const bad=structuredClone(m);change(bad.poolReadiness);assert.equal(numericalRunChecks(bad,'diagnostic').actualRestrictedPools,false);}});
test('actual report rows must fill each exact wave, range, school and scope',()=>{const m=minimal();m.phases[0].traffic={reports:[1,7,30,365].flatMap((days,wave)=>[0,1].flatMap(schoolIndex=>['school','grade','class','student'].flatMap(scope=>[0,1].map(()=>({wave,days,schoolIndex,scope,status:200,correct:true,durationMs:1})))))};assert.equal(numericalRunChecks(m,'diagnostic').fullReportMatrix,true);for(const change of [rows=>rows[0].wave=1,rows=>rows[0].scope='grade',rows=>rows[0].durationMs=-1,rows=>rows[0].status=503,rows=>rows.pop()]){const bad=structuredClone(m);change(bad.phases[0].traffic.reports);assert.equal(numericalRunChecks(bad,'diagnostic').fullReportMatrix,false);}});
test('eight CSV proofs must have distinct expected scopes and matching audit count',()=>{const m=minimal();m.correctness.csvAuditCount=8;m.correctness.exports=[0,1].flatMap(schoolIndex=>['school','grade','class','student'].map(scope=>({schoolIndex,scope,csvSha256:'a'.repeat(64),durationMs:1})));assert.equal(numericalRunChecks(m,'diagnostic').exactAuditedExports,true);m.correctness.exports[0].scope='grade';assert.equal(numericalRunChecks(m,'diagnostic').exactAuditedExports,false);});
