import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,readFileSync,existsSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {restoreWorkloadEnvironment,combinedCleanupReceipt,cleanupWorkloadResources,assertPreparedSchemaIdentity,prepareColdServices,finalizeRunEvidence,runRestoredRoleScale} from './run-restored-role-scale.mjs';
import {cleanupRoles} from './cleanup-role-fixtures.mjs';
const run='a'.repeat(12),source='b'.repeat(40),url='postgresql://synthetic:synthetic@127.0.0.1:5437/schoolpilot_redesign_usage_scale_'+run;
function input(){return{configuration:{appUrl:url,adminUrl:url},source,run,registry:{inventories:{classpilotPrivateChatLifecyclePostExpand:{tables:Array.from({length:129},(_,n)=>'table_'+n)}}},preparedStateSha256:'c'.repeat(64),phase:'combined',secret:()=> 'fresh-synthetic'};}
test('restored environment keeps full diagnostic profile, fresh secrets and existing restricted targets',()=>{const result=restoreWorkloadEnvironment(input());assert.equal(result.USAGE_RELEASE_PHASE,'combined');assert.equal(result.USAGE_RELEASE_CPU_PROFILE,'false');assert.equal(result.USAGE_RELEASE_DIAGNOSTIC,'true');assert.equal(result.DATABASE_URL_PRIVILEGED,url);assert.equal(result.RLS_ENABLED_TABLES.split(',').length,129);assert.equal(result.NODE_OPTIONS,undefined);assert.equal(result.DB_POOL_MAX,undefined);assert.equal(result.REDIS_URL,'redis://127.0.0.1:6387');});
for(const bad of ['postgresql://synthetic:synthetic@127.0.0.1:5437/other',url+'?host=remote',url.replace('127.0.0.1','remote'),url.replace(':5437',':5438')])test('restore cannot redirect workload connection '+bad.split('@').pop(),()=>assert.throws(()=>restoreWorkloadEnvironment({...input(),configuration:{appUrl:bad,adminUrl:url}})));
test('candidate path requires a real pending journal registration before fixture side effects',async()=>{await assert.rejects(()=>runRestoredRoleScale({mode:'capacity-candidate',phase:'combined'}));});
test('candidate environment keeps modern combined traffic distinct from diagnostics',()=>{const result=restoreWorkloadEnvironment({...input(),mode:'capacity-candidate'});assert.equal(result.USAGE_RELEASE_DIAGNOSTIC,'false');assert.equal(result.USAGE_RELEASE_CPU_PROFILE,'false');assert.throws(()=>restoreWorkloadEnvironment({...input(),mode:'capacity-candidate',phase:'ingest'}));});
test('candidate validator failure after successful workload cannot leave a successful CLI or canonical seal',()=>{const directory=mkdtempSync(join(tmpdir(),'schoolpilot-finalize-candidate-'));try{const exit=finalizeRunEvidence({directory,execution:{exitCode:0,diagnosticOnly:false},expectedRuntime:{},trustedPlanSha256:'a'.repeat(64),collect:()=>{},seal:()=>{writeFileSync(join(directory,'receipt-manifest.json'),'{}');return{bundle:{},receiptManifestSha256:'b'.repeat(64)};},validate:()=>({runPassed:false,capacityAccepted:false})});assert.equal(exit,1);assert.equal(JSON.parse(readFileSync(join(directory,'execution.json'))).exitCode,1);assert.equal(existsSync(join(directory,'receipt-manifest.json')),false);assert.equal(existsSync(join(directory,'receipt-manifest-unverified.json')),true);}finally{rmSync(directory,{recursive:true,force:true});}});
test('Redis joins the new PG namespace only after held release and completed cold restart',async()=>{const events=[],gate={},cold={after:{StartedAt:'2026-10-03T18:00:00Z'}};const result=await prepareColdServices({release:async()=>{events.push('release');return gate;},restart:async value=>{assert.equal(value,gate);events.push('restart');return cold;},createRedis:async value=>{assert.equal(value,cold);events.push('redis-new-namespace');return{id:'redis'};}});assert.deepEqual(events,['release','restart','redis-new-namespace']);assert.equal(result.cold,cold);});
test('failed cold restart cannot create Redis or launch a workload',async()=>{let created=false;await assert.rejects(()=>prepareColdServices({release:async()=>({}),restart:async()=>{throw Error('restart');},createRedis:async()=>{created=true;}}));assert.equal(created,false);});
for(const failure of ['runtime','seal','seal-after-manifest','validation','none','workload'])test(`final execution and CLI agree with preserved evidence: ${failure}`,()=>{const directory=mkdtempSync(join(tmpdir(),'schoolpilot-finalize-')),originalManifest='{"original":"unverified"}\n';let sealed=false;try{const exit=finalizeRunEvidence({directory,execution:{exitCode:failure==='workload'?1:0,capacityAccepted:false},expectedRuntime:{},trustedPlanSha256:'a'.repeat(64),collect:()=>{if(failure==='runtime')throw Error('runtime');},seal:()=>{sealed=true;if(failure==='seal')throw Error('seal');writeFileSync(join(directory,'receipt-manifest.json'),originalManifest);if(failure==='seal-after-manifest')throw Error('postwrite');return{bundle:{},receiptManifestSha256:'b'.repeat(64)};},validate:()=>{if(failure==='validation')throw Error('validation');return{runPassed:failure!=='workload',capacityAccepted:false};}});const failed=!['none','workload'].includes(failure);assert.equal(exit,failure==='none'?0:1);assert.equal(JSON.parse(readFileSync(join(directory,'execution.json'))).exitCode,exit);assert.equal(existsSync(join(directory,'receipt-collection-failure.json')),failed);assert.equal(existsSync(join(directory,'receipt-manifest.json')),!failed);if(failure==='runtime')assert.equal(sealed,false);if(['seal','seal-after-manifest','validation'].includes(failure))assert.equal(JSON.parse(readFileSync(join(directory,'execution-before-receipt-failure.json'))).exitCode,0);if(['seal-after-manifest','validation'].includes(failure))assert.equal(readFileSync(join(directory,'receipt-manifest-unverified.json'),'utf8'),originalManifest);}finally{rmSync(directory,{recursive:true,force:true});}});
test('actual wrapper schema guard distinguishes original fingerprint from native rendering',()=>{const schema={passed:true,originalCanonicalSha256:'1'.repeat(64),referenceCanonicalSha256:'2'.repeat(64),restoredCanonicalSha256:'2'.repeat(64),referenceNormalizedSha256:'3'.repeat(64),restoredNormalizedSha256:'3'.repeat(64)};assert.doesNotThrow(()=>assertPreparedSchemaIdentity(schema,'1'.repeat(64)));for(const key of ['originalCanonicalSha256','restoredCanonicalSha256','restoredNormalizedSha256'])assert.throws(()=>assertPreparedSchemaIdentity({...schema,[key]:'4'.repeat(64)},'1'.repeat(64)));assert.throws(()=>assertPreparedSchemaIdentity({...schema,passed:false},'1'.repeat(64)));});
for(const failing of ['roles','redis','both'])test(`independent workload cleanup survives ${failing} thrown failure`,async()=>{const called=[];const attempt=name=>async()=>{called.push(name);if(failing===name||failing==='both')throw Error('synthetic private error');return{cleanupPassed:true,confirmedAbsent:true};};const result=await cleanupWorkloadResources({roles:attempt('roles'),redis:attempt('redis')});assert.deepEqual(called.sort(),['redis','roles']);assert.equal(result.cleanupPassed,false);for(const name of called){assert.equal(result[name].cleanupPassed,!(failing===name||failing==='both'));if(!result[name].cleanupPassed){assert.equal(result[name].confirmedAbsent,false);assert.match(result[name].failureCode,/^(ROLE|REDIS)_CLEANUP_THREW$/);}}assert.equal(JSON.stringify(result).includes('synthetic private'),false);});
test('aggregate cleanup preserves failure instead of defaulting absent proof to true',()=>{const common={run,roles:{cleanupPassed:true,roles:[]},redis:{id:'1'.repeat(64),confirmedAbsent:true,cleanupPassed:true},postgres:{id:'2'.repeat(64),confirmedAbsent:true,cleanupPassed:true},finishedAt:new Date().toISOString()};assert.equal(combinedCleanupReceipt(common).cleanupPassed,true);for(const key of ['confirmedAbsent','cleanupPassed']){const bad=structuredClone(common);delete bad.redis[key];assert.equal(combinedCleanupReceipt(bad).cleanupPassed,false);}});
function owner(){const directory=mkdtempSync(join(tmpdir(),'schoolpilot-role-cleanup-')),image='sha256:'+'c'.repeat(64),roles=['api','worker','generator','coordinator'].map((role,n)=>({role,containerId:String(n+1).repeat(64),exit:{forced:false}}));writeFileSync(join(directory,'role-host-result.json'),JSON.stringify({run,imageId:image,roles}));return{directory,image,roles};}
test('malformed actual role receipt still removes exact-owned Redis through independent cleanup',async()=>{const{directory,image}=owner();let removed=false;const redisId='9'.repeat(64),owned={Id:redisId,Name:'/schoolpilot-usage-redis-'+run,Config:{Labels:{'codex.usage-scale':run}}};try{writeFileSync(join(directory,'role-host-result.json'),'{invalid');const result=await cleanupWorkloadResources({roles:()=>cleanupRoles({inspect:async()=>null,remove:async()=>assert.fail('invalid role receipt')},{run,output:directory,image}),redis:async()=>{assert.equal(owned.Id,redisId);assert.equal(owned.Config.Labels['codex.usage-scale'],run);removed=true;return{id:redisId,cleanupPassed:true,confirmedAbsent:true};}});assert.equal(removed,true);assert.equal(result.roles.failureCode,'ROLE_CLEANUP_THREW');assert.equal(result.redis.id,redisId);assert.equal(result.redis.cleanupPassed,true);assert.equal(result.cleanupPassed,false);}finally{rmSync(directory,{recursive:true,force:true});}});
test('post-host cleanup binds each actual removed ID and checks exact ID plus name absence',async()=>{const {directory,image,roles}=owner(),checked=[];try{const result=await cleanupRoles({inspect:async value=>{checked.push(value);return null;},remove:async()=>assert.fail('already removed')},{run,output:directory,image});assert.equal(result.cleanupPassed,true);for(const row of roles){assert.ok(checked.includes(row.containerId));assert.ok(checked.includes('schoolpilot-role-'+row.role+'-'+run));assert.equal(result.roles.find(x=>x.role===row.role).id,row.containerId);assert.equal(result.roles.find(x=>x.role===row.role).forced,false);}}finally{rmSync(directory,{recursive:true,force:true});}});
test('missing name cannot hide a renamed or unverifiable owned ID',async()=>{const {directory,image,roles}=owner();try{const result=await cleanupRoles({inspect:async value=>value===roles[0].containerId?{Id:value}:null,remove:async()=>assert.fail('unexpected')},{run,output:directory,image});assert.equal(result.cleanupPassed,false);assert.equal(result.roles.find(x=>x.role==='api').cleanupPassed,false);}finally{rmSync(directory,{recursive:true,force:true});}});
