import test from 'node:test';
import assert from 'node:assert/strict';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {assertRestoreOptions,compareNativeSchemas,verifyOwnedSnapshotContainer,cleanupRestoredSnapshot,assertUnexpiredRestoreGate} from './restore-snapshot.mjs';
const options=()=>({run:'a'.repeat(12),source:'b'.repeat(40),snapshotManifestSha256:'c'.repeat(64),endpoint:'npipe:////./pipe/dockerDesktopLinuxEngine',sourceDirectory:join(tmpdir(),'restore-source'),snapshotDirectory:join(tmpdir(),'restore-snapshot'),evidenceDirectory:join(tmpdir(),'restore-evidence'),privateDirectory:join(tmpdir(),'restore-private'),mode:'diagnostic',purpose:'Bounded synthetic restore proof'});
test('cold restart refuses an expired hold or insufficient unchanged authority horizon',()=>{const now=Date.parse('2026-10-03T18:00:00Z'),iso=n=>new Date(n).toISOString(),input={now,ready:{readyAt:iso(now-1000),expiresAt:iso(now+60000)},gate:{releasedAt:iso(now-500)},validityHorizon:iso(now+960000)};assert.doesNotThrow(()=>assertUnexpiredRestoreGate(input));for(const patch of [{now:now+60000},{validityHorizon:iso(now+899999)},{gate:{releasedAt:iso(now+1)}},{gate:{releasedAt:iso(now-1001)}},{validityHorizon:'invalid'}])assert.throws(()=>assertUnexpiredRestoreGate({...input,...patch}));});
test('restore paths are separate and diagnostic execution remains fail closed',()=>{const o=options();assert.equal(assertRestoreOptions(o),o);for(const patch of [{mode:'capacity-candidate'},{endpoint:'tcp://127.0.0.1:2375'},{endpoint:'ssh://remote'},{privateDirectory:o.evidenceDirectory},{privateDirectory:join(o.evidenceDirectory,'private')},{privateDirectory:join(o.evidenceDirectory,'..private')},{source:'mutable'},{snapshotManifestSha256:'bad'}])assert.throws(()=>assertRestoreOptions({...o,...patch}));});
test('native reference comparison binds both complete renderings without CHECK normalization',()=>{const original='CHECK ((a AND (b AND c)))\n';const reference='\\restrict ref\nCHECK ((a AND b AND c))\n\\unrestrict ref\n';const restored='\uFEFF\\restrict restored\r\nCHECK ((a AND b AND c))\r\n\\unrestrict restored\r\n';const proof=compareNativeSchemas(original,reference,restored);assert.equal(proof.passed,true);assert.equal(proof.referenceNormalizedSha256,proof.restoredNormalizedSha256);assert.notEqual(proof.referenceSha256,proof.restoredSha256);assert.throws(()=>compareNativeSchemas(original,reference,restored.replace('b AND c','b OR c')));assert.throws(()=>compareNativeSchemas(original,reference,restored+'ALTER TABLE x DISABLE ROW LEVEL SECURITY;'));});
function fixture(){const expected={run:'a'.repeat(12),name:'schoolpilot-usage-scale-'+'a'.repeat(12),image:'sha256:'+'b'.repeat(64),imageInspect:{RootFS:{Layers:['one']},Config:{Env:['PG_MAJOR=16']}}};const actual=structuredClone(expected.imageInspect);const found={Name:'/'+expected.name,Id:'c'.repeat(64),Config:{Labels:{'codex.usage-snapshot-restore':expected.run,'codex.usage-scale':expected.run},Image:expected.image},Mounts:[{Type:'volume',Destination:'/var/lib/postgresql/data',Name:'d'.repeat(64),RW:true}],HostConfig:{Binds:null,NanoCpus:4e9,Memory:4*1024**3,MemorySwap:4*1024**3,Privileged:false,PortBindings:{'5437/tcp':[{HostIp:'127.0.0.1',HostPort:'5437'}]}}};return{expected,actual,found};}
test('cleanup proof uses immutable requested image and verified runtime image content',()=>{const {expected,actual,found}=fixture();assert.equal(verifyOwnedSnapshotContainer(found,expected,actual),found);for(const mutate of [x=>x.Config.Labels['codex.usage-snapshot-restore']='other',x=>x.Config.Image='mutable',x=>x.HostConfig.Memory*=2,x=>x.HostConfig.PortBindings['5437/tcp'][0].HostIp='0.0.0.0',x=>x.Name='/unrelated']){const changed=structuredClone(found);mutate(changed);assert.throws(()=>verifyOwnedSnapshotContainer(changed,expected,actual));}assert.throws(()=>verifyOwnedSnapshotContainer(found,expected,{...actual,RootFS:{Layers:['other']}}));});
test('unknown create outcome recovers exact owned container then verifies successful absence',async()=>{const {found}=fixture(),events=[],receipts=[];let current=found;const receipt=await cleanupRestoredSnapshot({run:'a',name:'name',id:null,created:false,handoffPassed:false,failure:{stage:'create'},find:async()=>{events.push('find');return current;},verify:async x=>{assert.equal(x,found);events.push('verify');},remove:async id=>{assert.equal(id,found.Id);events.push('remove');current=null;},saveReceipt:x=>receipts.push(x)});assert.deepEqual(events,['find','verify','remove','find']);assert.equal(receipt.confirmedAbsent,true);assert.equal(receipt.containerId,found.Id);assert.equal(receipts.length,1);});
for(const failure of ['initial-list','verification','remove','final-list','still-present','different-id'])test(`cleanup cannot certify ${failure} as absence`,async()=>{const {found}=fixture(),receipts=[];let calls=0,removed=0;await assert.rejects(()=>cleanupRestoredSnapshot({run:'a',name:'name',id:failure==='different-id'?'d'.repeat(64):found.Id,created:true,handoffPassed:true,failure:null,find:async()=>{calls++;if((failure==='initial-list'&&calls===1)||(failure==='final-list'&&calls===2))throw Error('daemon');return calls===1||failure==='still-present'?found:null;},verify:async()=>{if(failure==='verification')throw Error('ownership');},remove:async()=>{removed++;if(failure==='remove')throw Error('remove');},saveReceipt:x=>receipts.push(x)}));assert.equal(receipts.length,1);assert.equal(receipts[0].cleanupPassed,false);assert.equal(receipts[0].confirmedAbsent,false);if(['initial-list','verification','different-id'].includes(failure))assert.equal(removed,0);});
test('container removal does not certify an unconfirmed anonymous-volume cleanup',async()=>{const receipts=[];await assert.rejects(()=>cleanupRestoredSnapshot({run:'a',name:'name',id:'a'.repeat(64),created:true,handoffPassed:true,find:async()=>null,verify:async()=>{},remove:async()=>{},verifyVolumesAbsent:async()=>{throw Error('volume remains');},saveReceipt:r=>receipts.push(r)}));assert.equal(receipts[0].cleanupPassed,false);});
