import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {assertSnapshotManifest,loadSnapshot,normalizeSnapshotSchema,snapshotHash} from './snapshot-contract.mjs';
const source='a'.repeat(40),today='2026-10-03';
const names=['prepared-database.private.dump','synthetic-roles.private.sql','cold-fixture-state.json','release-control-preparation.json','preparation-fixture-contract.json','preparation-metrics.json','schema-fingerprint.json','post-convergence-schema.sql','measurement-ready.json'];
function manifest(){return {schemaVersion:1,source,preparedSchoolLocalDate:today,sourceUnchanged:true,timingHeld:true,measurementGoAbsent:true,readOnlyExport:true,otherClientsBefore:0,otherClientsAfter:0,timezone:'UTC',databaseEncoding:'UTF8',serverVersion:'16.15',heartbeatRows:2000002,migrations:54,schoolCounts:[{schoolIndex:0,observations:1000001},{schoolIndex:1,observations:1000001}],pgImage:'sha256:'+'a'.repeat(64),records:names.map(file=>({file,sha256:snapshotHash('{}'),bytes:2}))};}
test('immutable snapshot contract accepts only the exact same-source prepared fixture',()=>assert.equal(assertSnapshotManifest(manifest(),{source,today}).source,source));
for(const [name,mutate] of Object.entries({source:m=>m.source='b'.repeat(40),date:m=>m.preparedSchoolLocalDate='2026-10-02',openClient:m=>m.otherClientsAfter=1,unfrozen:m=>m.sourceUnchanged=false,measurementStarted:m=>m.measurementGoAbsent=false,timezone:m=>m.timezone='America/New_York',version:m=>m.serverVersion='16.14',rowCount:m=>m.heartbeatRows--,schoolDuplicate:m=>m.schoolCounts[1].schoolIndex=0,migrationCount:m=>m.migrations--,recordDuplicate:m=>m.records[1]={...m.records[0]},path:m=>m.records[0].file='../dump'}))test(`snapshot rejects ${name}`,()=>{const m=manifest();mutate(m);assert.throws(()=>assertSnapshotManifest(m,{source,today}));});
test('snapshot loader verifies every private and public file byte without rewriting',()=>{const dir=mkdtempSync(join(tmpdir(),'role-snapshot-contract-'));try{const m=manifest();for(const name of names)writeFileSync(join(dir,name),'{}');writeFileSync(join(dir,'manifest.json'),JSON.stringify(m));const hash=snapshotHash(readFileSync(join(dir,'manifest.json')));assert.equal(loadSnapshot(dir,hash,{source,today}).manifest.source,source);writeFileSync(join(dir,'prepared-database.private.dump'),'{x');assert.throws(()=>loadSnapshot(dir,hash,{source,today}));}finally{rmSync(dir,{recursive:true,force:true});}});
test('schema comparison removes only pg_dump nonce directives and line endings',()=>{assert.equal(normalizeSnapshotSchema('\\restrict old\r\nCREATE TABLE x(a int);\r\n\\unrestrict old\r\n'),normalizeSnapshotSchema('\\restrict new\nCREATE TABLE x(a int);\n\\unrestrict new\n'));assert.notEqual(normalizeSnapshotSchema('CREATE TABLE x(a int);'),normalizeSnapshotSchema('CREATE TABLE x(a text);'));});
