export const adminGuidePhases = ["Launch", "People and Classes", "Policies", "Operations", "Support"];

export const adminGuideTopics = [
  {
    id: "launch-checklist",
    phase: "Launch",
    title: "Launch checklist",
    summary: "Bring staff, students, classes, schedules, and managed Chromebooks online in a safe order.",
    keywords: ["setup", "launch", "staff", "students", "pin", "classes", "calendar", "managed policy", "readiness"],
    role: "Administrator or school administrator",
    route: "/classpilot/admin/it-readiness",
    routeLabel: "Open IT Readiness",
    steps: [
      { title: "Establish school identity", body: "Confirm the school name, Workspace domain, timezone, and active ClassPilot entitlement." },
      { title: "Create people and classes", body: "Add staff, import students, configure shared-device PINs when used, and build official classes with teachers, rosters, and schedules." },
      { title: "Configure managed Chrome", body: "Generate a setup key, place the ClassPilot managed policy in Google Admin, and force-install the correct extension ID for the intended organizational units." },
      { title: "Review the calendar and readiness", body: "Confirm instructional dates, Google connection status, extension check-ins, and every IT Readiness warning before the first live class." },
      { title: "Pilot before expanding", body: "Test with separate administrator, teacher, and student accounts on managed Chromebooks before enabling a whole school." },
    ],
    warning: "A public Store version does not prove managed Chromebooks have adopted it. Use device check-ins and accepted capabilities.",
  },
  {
    id: "staff-and-access",
    phase: "People and Classes",
    title: "Manage staff and access",
    summary: "Create staff, assign the least privilege, and keep lifecycle actions auditable.",
    keywords: ["staff", "import", "role", "password reset", "disable", "delete", "audit log", "active session"],
    role: "Administrator or school administrator",
    route: "/classpilot/admin",
    routeLabel: "Open Admin Panel",
    steps: [
      { title: "Create or import staff", body: "Add staff individually or use an available Workspace import. Staff email domains must match the school’s configured Workspace domain." },
      { title: "Assign roles intentionally", body: "Use administrator, school administrator, teacher, and office roles according to job duties. Review multi-role staff instead of relying only on the displayed primary role." },
      { title: "Handle account support", body: "Use password reset and lifecycle actions from the staff record. Avoid sharing temporary credentials in tickets or guide notes." },
      { title: "Review active sessions and logs", body: "Use current session information and audit logs to investigate changes before disabling or removing access." },
    ],
    warning: "Disabling or deleting access can interrupt active work. Verify the exact staff record and school first.",
  },
  {
    id: "students-and-pins",
    phase: "People and Classes",
    title: "Manage students and shared-device PINs",
    summary: "Use student records for identity and roster membership—not as a device-assignment screen.",
    keywords: ["students", "csv", "workspace", "import", "grade", "pin", "bulk", "roster"],
    role: "Administrator or school administrator",
    route: "/classpilot/students",
    routeLabel: "Open Students",
    steps: [
      { title: "Choose an import path", body: "Create students manually or import by CSV or Workspace. Review validation results and resolve duplicates by exact school identity." },
      { title: "Complete student identity", body: "Confirm names, school email addresses, student IDs, and grade levels. These fields support sign-in and class imports." },
      { title: "Manage PINs", body: "Generate, reset, or print shared-device PINs only for the students who need them. Treat printed PIN sheets as protected school records." },
      { title: "Use bulk actions narrowly", body: "Filter and review the selected students before applying a bulk change." },
    ],
    tips: ["Students holds school student records. Roster manages class membership. Neither page manually binds a student to a Chromebook."],
  },
  {
    id: "chromebooks",
    phase: "People and Classes",
    title: "Review managed Chromebooks",
    summary: "Use extension check-in data to troubleshoot deployment and readiness.",
    keywords: ["chromebook", "device", "extension version", "check in", "stale", "capability", "google admin"],
    role: "Administrator or school administrator",
    route: "/classpilot/roster",
    routeLabel: "Open Roster and Chromebook status",
    steps: [
      { title: "Separate records from devices", body: "Use student and class pages for people. Use Chromebook status for managed browser check-ins and extension readiness." },
      { title: "Check version and freshness", body: "Compare the reported extension version, last check-in, and accepted capabilities. Unknown or old clients remain unavailable for features they cannot enforce safely." },
      { title: "Repair through Google Admin", body: "Confirm organizational-unit targeting, force-install status, and managed policy. Then allow the Chromebook to reconnect and report current capability data." },
      { title: "Avoid manual pairing", body: "Student authority is established by authenticated session and managed-device continuity, not by assigning a device ID in the admin interface." },
    ],
  },
  {
    id: "classes-and-schedules",
    phase: "People and Classes",
    title: "Build classes, rosters, and schedules",
    summary: "Official classes define teacher authority, student membership, and scheduled session windows.",
    keywords: ["classes", "classroom import", "primary teacher", "co-teacher", "schedule", "roster", "archive", "delete", "schedule change"],
    role: "Administrator or school administrator",
    route: "/classpilot/admin/classes",
    routeLabel: "Open Classes",
    steps: [
      { title: "Create or import", body: "Create an official class or import from Google Classroom, then verify its school, name, and source." },
      { title: "Assign teaching staff", body: "Set one primary teacher and any appropriate co-teachers. These assignments control who can start and operate the class." },
      { title: "Build the roster", body: "Add the exact students who belong in the class. A student can belong to more than one official class." },
      { title: "Configure the recurring window", body: "Set the class schedule and school calendar. Review conflicts before enabling automatic start and end." },
      { title: "Use archive or delete deliberately", body: "Archive when history must remain available. Delete only when the UI confirms the action is appropriate and irreversible consequences are understood." },
    ],
  },
  {
    id: "schedule-change-operations",
    phase: "People and Classes",
    title: "Operate one-day schedule changes",
    summary: "Configure eligible pairs and approve dated exceptions without rewriting recurring schedules.",
    keywords: ["schedule change", "time swap", "approval", "pair", "cancel", "history"],
    role: "Administrator or school administrator",
    route: "/classpilot/admin/classes/schedule-changes",
    routeLabel: "Open schedule changes",
    steps: [
      { title: "Define eligible pairs", body: "Pair active scheduled classes whose periods meet the compatibility rules." },
      { title: "Review requests", body: "Approve or deny teacher requests according to school policy, timing, and the reason provided." },
      { title: "Create an administrator change", body: "Create a dated change directly when needed and record a clear reason." },
      { title: "Cancel before the boundary", body: "Cancel an approved future change only before either effective class begins. Use history for an auditable record." },
    ],
  },
  {
    id: "school-settings",
    phase: "Policies",
    title: "Configure school settings and privacy boundaries",
    summary: "Set school-wide defaults without confusing them with an individual administrator’s teaching tools.",
    keywords: ["school name", "retention", "tab limit", "allowed domains", "blocked domains", "safety email", "central email", "shared sign in", "setup key", "managed policy", "privacy"],
    role: "Administrator or school administrator",
    route: "/classpilot/settings",
    routeLabel: "Open School Settings",
    steps: [
      { title: "Set core boundaries", body: "Review school identity, retention, tab limits, allowed domains, blocked domains, and safety notification recipients." },
      { title: "Configure shared sign-in", body: "Enable shared Chromebook sign-in only when the school’s device model requires it, then manage setup keys as protected configuration." },
      { title: "Deploy managed policy", body: "Copy the generated managed policy to the exact Google Admin application configuration. Rotate a setup key when exposure is suspected." },
      { title: "Set workflow policy", body: "Review the schedule-change policy and other school-level controls before teachers depend on them." },
      { title: "Respect data boundaries", body: "Use retention and access controls according to school policy. Do not copy student browsing or sign-in details into general-purpose notes." },
    ],
    tips: ["Flight Paths displayed in School Settings belong to the signed-in administrator’s teaching profile; they are not a school-wide library."],
  },
  {
    id: "student-sign-in-policy",
    phase: "Policies",
    title: "Allow student sign-in during restrictions",
    summary: "Configure the exact identity providers students may use while a Waypoint or Flight Path remains authoritative.",
    keywords: ["sso", "clever", "google", "microsoft", "okta", "classlink", "waypoint", "flight path", "provider", "extension readiness"],
    role: "Administrator or school administrator",
    route: "/classpilot/settings",
    routeLabel: "Open Student Sign-In policy",
    steps: [
      { title: "Open Student Sign-In During Waypoints", body: "Enable the policy only after reviewing extension readiness. Choose the provider that a cold restricted session should open first." },
      { title: "Configure providers", body: "Use the built-in Google or Clever profile, enter the district Clever launch address when required, or add a bounded custom provider for the school’s identity system." },
      { title: "Approve exact hosts", body: "Prefer exact hostnames. Allow subdomains only when the provider genuinely requires them. Lookalikes, wildcards, public suffixes, local addresses, and unsafe URLs are rejected." },
      { title: "Resolve policy conflicts", body: "Attention, school blocks, and teacher blocks remain higher priority than sign-in pass-through. Resolve warnings when an approved provider is also blocked." },
      { title: "Verify the full round trip", body: "Test provider start, any Google Accounts handoff, callback, and the final learning destination. A provider visit alone is not completion." },
      { title: "Roll out by capability", body: "Keep the operator capability off until the extension is deployed. Enable only after recently active devices report the raw and accepted restrictionAuthPassThroughV1 capability." },
    ],
    warning: "The policy authorizes only configured identity-provider hosts for a five-minute attempt. It never creates general web access and never overrides a school or teacher block.",
  },
  {
    id: "coverage-administration",
    phase: "Operations",
    title: "Administer Coverage",
    summary: "Define who can temporarily supervise students and preserve clear ownership through claim and release.",
    keywords: ["coverage", "permission", "supervision group", "assignment", "claim", "release", "reroute", "history"],
    role: "Administrator or school administrator",
    route: "/classpilot/coverage",
    routeLabel: "Open Coverage",
    steps: [
      { title: "Set permissions and groups", body: "Choose the staff and supervision groups that may receive coverage assignments." },
      { title: "Assign exact students", body: "Create the assignment with its intended staff, students, and time boundary. Do not use missing targets as a broader fallback." },
      { title: "Watch ownership transitions", body: "Claim, reroute, and release operations update who controls the student. Wait for the new context before sending actions." },
      { title: "Review controls and history", body: "Coverage exposes a bounded control set. Use history to confirm who claimed, acted, and released an assignment." },
    ],
  },
  {
    id: "analytics-readiness-safety",
    phase: "Operations",
    title: "Use Analytics, IT Readiness, and Safety Center",
    summary: "Keep operational health, instructional trends, and evidence workflows in their proper contexts.",
    keywords: ["analytics", "it readiness", "safety center", "evidence", "audit", "google connectivity", "preview"],
    role: "Administrator or school administrator",
    route: "/classpilot/admin/analytics",
    routeLabel: "Open Analytics",
    steps: [
      { title: "Review trends", body: "Use Analytics for school, teacher, class, and student activity patterns within the selected time period." },
      { title: "Resolve readiness findings", body: "Use IT Readiness for Google domain mismatches, reconnect requirements, staff identity findings, and extension deployment gaps." },
      { title: "Work safety cases", body: "Use Safety Center to review alerts in context, document a decision, and create evidence only when school procedure requires it." },
      { title: "Keep evidence scoped", body: "Evidence workflows preserve the authorized school, student, class, and time context. Export and share only through approved school processes." },
    ],
  },
  {
    id: "email-monitoring",
    phase: "Operations",
    title: "Operate Email Monitoring",
    summary: "Set up and review the ClassPilot email-safety add-on when the school is entitled.",
    keywords: ["mailpilot", "email monitoring", "gmail", "domain wide delegation", "alerts", "review"],
    role: "Administrator; entitlement is granted by a super administrator",
    entitlement: "mailpilot",
    route: "/classpilot/admin/email-monitoring",
    routeLabel: "Open Email Monitoring",
    steps: [
      { title: "Confirm entitlement", body: "A super administrator must grant the add-on to an active ClassPilot school before setup is available." },
      { title: "Authorize Workspace access", body: "Follow the setup wizard to add the displayed client ID and read-only Gmail scope in Google Admin domain-wide delegation." },
      { title: "Verify and enable", body: "Test with one school mailbox, then enable watches for eligible student addresses." },
      { title: "Review alerts", body: "Confirm, dismiss, or escalate alerts according to school policy, preserving the audit trail and limiting access to authorized staff." },
    ],
  },
  {
    id: "cleanup-and-recovery",
    phase: "Support",
    title: "Clean up safely and recover service",
    summary: "Troubleshoot from the least destructive check to the most consequential action.",
    keywords: ["troubleshoot", "google", "import", "stale chromebook", "setup key", "permissions", "calendar conflict", "delete", "archive", "reset"],
    role: "Administrator or school administrator",
    route: "/classpilot/admin/it-readiness",
    routeLabel: "Open IT Readiness",
    steps: [
      { title: "Identify the boundary", body: "Determine whether the problem is identity, Google connectivity, import validation, class authority, calendar policy, managed Chrome, or current student connection." },
      { title: "Refresh safe state", body: "Reconnect Google when required, correct source data, resync the affected class, or allow the managed Chromebook to check in again." },
      { title: "Repair configuration", body: "Verify the extension ID, managed policy, setup key, organizational-unit assignment, permissions, and school-local calendar windows." },
      { title: "Use lifecycle actions last", body: "Archive before delete when history must remain. Reset credentials or PINs only for the exact account. Record the reason for irreversible actions." },
      { title: "Escalate with safe evidence", body: "Provide timestamps, displayed status, extension version, accepted-capability state, and non-sensitive error text. Never include passwords, tokens, cookies, or redirect query strings." },
    ],
    warning: "Delete, key rotation, account disablement, and bulk roster changes can interrupt active classes. Confirm the exact school and affected records before continuing.",
  },
];
