export const teacherGuidePhases = ["Prepare", "Start", "Guide", "Monitor", "Wrap Up"];

export const teacherGuideTopics = [
  {
    id: "prepare-your-class",
    phase: "Prepare",
    title: "Prepare your class",
    summary: "Check the roster, choose a class, and set up the tools you expect to use before the bell.",
    keywords: ["roster", "class", "schedule", "subgroup", "flight path", "block list", "tab limit"],
    role: "Teacher or administrator",
    route: "/classpilot/my-settings",
    routeLabel: "Open teaching tools",
    steps: [
      { title: "Review your assigned classes", body: "Confirm the class and students you expect to teach. Ask an administrator to correct official class membership or teacher assignments." },
      { title: "Build reusable tools", body: "Create personal Flight Paths, Block Lists, and subgroups in My Settings. Flight Paths allow only their listed destinations; Block Lists deny their listed domains." },
      { title: "Choose classroom defaults", body: "Set your preferred tab limit and default Flight Path. School policy can be stricter than a personal preference." },
      { title: "Check today’s schedule", body: "If your school permits one-day schedule changes, review requests and approved changes before class begins." },
    ],
    tips: ["Use clear names such as “Period 2 Research” so the right tool is easy to find during class."],
  },
  {
    id: "schedule-changes",
    phase: "Prepare",
    title: "Request a one-day schedule change",
    summary: "Exchange the scheduled time of an eligible class for one instructional day without changing teachers or rosters.",
    keywords: ["schedule change", "time swap", "request", "accept", "class time"],
    role: "Primary teacher; school policy may require approval",
    route: "/classpilot/my-settings/schedule-changes",
    routeLabel: "Open schedule changes",
    steps: [
      { title: "Start a request", body: "Choose an eligible class pair and instructional date, then review the normal and proposed times." },
      { title: "Add context", body: "Enter a reason when required by school policy and send the request to the other primary teacher." },
      { title: "Track the decision", body: "Use Needs Action, Upcoming, and History. A request changes nothing until every required acceptance and approval is complete." },
    ],
    warning: "A same-day change cannot begin after either affected class has already started.",
  },
  {
    id: "start-and-resync",
    phase: "Start",
    title: "Start, resync, skip, or end class",
    summary: "Use the class controls deliberately so monitoring and student controls follow the correct teaching session.",
    keywords: ["start class", "resync", "skip today", "end class", "session"],
    role: "Assigned class teacher",
    route: "/classpilot",
    routeLabel: "Open Dashboard",
    steps: [
      { title: "Select the class", body: "Choose the class you are teaching. Scheduled classes can start only inside their effective window." },
      { title: "Start the session", body: "Start class and wait for the roster and connection states to settle before sending controls." },
      { title: "Resync when needed", body: "Use Resync if the roster or current session appears out of date. Resync refreshes authority; it does not broaden your class access." },
      { title: "Skip or end intentionally", body: "Skip Today prevents the scheduled occurrence from starting. End Class closes the current session and begins wrap-up processing." },
    ],
    tips: ["If the wrong class is active, end it before starting another one; do not try to control students from a stale class view."],
  },
  {
    id: "read-dashboard-status",
    phase: "Start",
    title: "Read Dashboard status correctly",
    summary: "Connection freshness, previews, and sign-in state are separate signals.",
    keywords: ["online", "idle", "signed out", "signal lost", "stale", "preview", "counters", "signing in"],
    role: "Teacher or administrator",
    route: "/classpilot",
    routeLabel: "Open Dashboard",
    steps: [
      { title: "Use the counters", body: "Online and Idle students have current heartbeat coverage. Signed-out students have no active ClassPilot student session. Signal Lost means a signed-in browser has stopped reporting; the cause is not assumed." },
      { title: "Treat previews as passive evidence", body: "A screen preview is an authorized still image with its own age. It does not determine whether a student is connected and it never replaces heartbeat status." },
      { title: "Recognize transitions", body: "Signing in means an approved identity-provider flow is active. Updating preview means a new control revision is waiting for its matching still image. Neither label means the student is stale." },
      { title: "Wait for exact authority", body: "When a student changes device or session, ClassPilot clears prior-session details before showing the new binding." },
    ],
    warning: "Do not interpret a recent preview as proof that commands are currently available. Use the connection label and command outcome.",
  },
  {
    id: "target-and-interpret-results",
    phase: "Guide",
    title: "Target exact students and read results",
    summary: "ClassPilot never turns a missing target into a class-wide action.",
    keywords: ["select all", "checkbox", "student selection", "applied", "pending", "unavailable", "results"],
    role: "Assigned or coverage teacher",
    route: "/classpilot",
    routeLabel: "Open Dashboard",
    steps: [
      { title: "Choose the scope", body: "Use student checkboxes, Select All, or a subgroup. Recheck the selected count before confirming the action." },
      { title: "Send the command", body: "ClassPilot resolves the exact students and their current sessions. It does not substitute another device or student when a target is missing." },
      { title: "Read every outcome", body: "Applied is enforced now. Pending is waiting for an eligible connection. Unavailable means the action cannot safely reach that student, such as when an extension update is required." },
      { title: "Follow up narrowly", body: "Retry only the students who need it after their status changes. A partial result is not a reason to resend to the whole class." },
    ],
    tips: ["The result summary can contain both pending and unavailable students; review both counts."],
  },
  {
    id: "open-url-and-tabs",
    phase: "Guide",
    title: "Open a URL and manage tabs",
    summary: "Send learning resources and close the exact tabs shown for a student.",
    keywords: ["open url", "send to", "manage tabs", "close tabs", "tab limit"],
    role: "Assigned or coverage teacher",
    route: "/classpilot",
    routeLabel: "Open Dashboard",
    steps: [
      { title: "Open a resource", body: "Select the intended students, choose Open URL, and verify the address before sending." },
      { title: "Inspect current tabs", body: "Use Manage Tabs to review the current tab inventory for each selected student." },
      { title: "Close exact rows", body: "Choose the specific tab rows to close, or use Close All when that is truly intended. Duplicate addresses remain separate tabs." },
      { title: "Use tab limits carefully", body: "A tab limit manages tab count but preserves the last usable destination and an active school-approved sign-in flow." },
    ],
  },
  {
    id: "waypoints-and-flight-paths",
    phase: "Guide",
    title: "Use Waypoints and Flight Paths",
    summary: "A Waypoint directs students to one page; a Flight Path confines browsing to a prepared set of destinations.",
    keywords: ["waypoint", "flight path", "current page", "signed out", "clever", "google", "sso", "sign in"],
    role: "Assigned or coverage teacher",
    route: "/classpilot",
    routeLabel: "Open Dashboard",
    steps: [
      { title: "Choose the restriction", body: "Use a Waypoint for one exact destination or apply a Flight Path for a bounded set of learning destinations." },
      { title: "Account for signed-out students", body: "A saved destination can wait for eligible signed-out students. A Current Page Waypoint cannot resolve a signed-out student’s page, so those students are skipped and counted." },
      { title: "Allow school-approved sign-in", body: "If the destination redirects to an approved provider such as Clever or Google Accounts, the student can complete sign-in without escaping the restriction. ClassPilot shows Signing in and returns to the assigned destination afterward." },
      { title: "Remove the right control", body: "Unlock removes a Waypoint screen lock without silently deleting an active Flight Path. Remove Flight Path is a separate action." },
    ],
    warning: "An identity-provider page is temporary authentication, not proof that the student reached the assigned learning destination.",
  },
  {
    id: "focus-and-communication",
    phase: "Guide",
    title: "Use focus and communication tools",
    summary: "Apply the least disruptive classroom tool that solves the moment.",
    keywords: ["block list", "attention", "message", "hand raise", "poll", "timer", "clear"],
    role: "Assigned class teacher; coverage has a smaller tool set",
    route: "/classpilot",
    routeLabel: "Open Dashboard",
    steps: [
      { title: "Block a defined set", body: "Apply or remove one of your saved Block Lists. School and teacher blocks remain authoritative during sign-in." },
      { title: "Use Attention briefly", body: "Attention takes precedence over every browsing exception. Turn it off as soon as the class is ready to continue." },
      { title: "Communicate in context", body: "Use teacher messages, hand raises, polls, and timers only inside the active class that owns those tools." },
      { title: "Clear before the next sign-in", body: "When a restriction should not follow a student into the next session, clear it before sign-in and verify the resulting status." },
    ],
  },
  {
    id: "student-drawer-and-history",
    phase: "Monitor",
    title: "Use the student drawer responsibly",
    summary: "Review current context and authorized history without treating one signal as the whole story.",
    keywords: ["student drawer", "activity history", "timeline", "preview", "responsible monitoring"],
    role: "Authorized teacher or administrator",
    route: "/classpilot",
    routeLabel: "Open Dashboard",
    steps: [
      { title: "Open the exact student", body: "Select a student tile to see current context, browsing history, and the passive preview authorized for this class." },
      { title: "Check time and context", body: "Review timestamps, class ownership, attendance or pass context, and status before drawing a conclusion from a title or domain." },
      { title: "Use educational purpose", body: "Monitor only for legitimate instruction, safety, and support. Follow school policy for documentation or escalation." },
      { title: "Close when finished", body: "Exit the drawer when the focused review is complete so the normal class view remains clear." },
    ],
    warning: "A page title, category, or still image can be incomplete. Confirm context before intervening.",
  },
  {
    id: "coverage-workflow",
    phase: "Monitor",
    title: "Work an assigned Coverage session",
    summary: "Claim only assigned students, use the coverage tool set, and release them when supervision ends.",
    keywords: ["coverage", "claim", "release", "send to", "supervision group"],
    role: "Staff member with a Coverage assignment",
    route: "/classpilot/coverage",
    routeLabel: "Open Coverage",
    steps: [
      { title: "Open Available", body: "Review students made available to your supervision group and claim only the assignment you are taking." },
      { title: "Confirm Claimed", body: "Wait for the claimed context to load before sending an action. The class owner and exact student bindings remain authoritative." },
      { title: "Use coverage controls", body: "Send resources, manage allowed tabs and restrictions, message students, or apply the controls shown in Coverage. Tools not shown are not part of Coverage authority." },
      { title: "Release cleanly", body: "Release the students when supervision ends so control returns to the correct class context." },
    ],
  },
  {
    id: "wrap-up-and-troubleshoot",
    phase: "Wrap Up",
    title: "Wrap up and troubleshoot",
    summary: "End the session, review outcomes, and know when an administrator must help.",
    keywords: ["end class", "summary", "troubleshoot", "extension update", "managed configuration", "administrator"],
    role: "Teacher or administrator",
    route: "/classpilot",
    routeLabel: "Return to Dashboard",
    steps: [
      { title: "Remove temporary controls", body: "Clear controls that should not persist, then end class and wait for the session to close." },
      { title: "Review the summary", body: "Check the session summary and any pending or unavailable outcomes that need later follow-up." },
      { title: "Retry connection issues once", body: "Resync the class after a student reconnects. Do not repeatedly broadcast a command while the student remains unavailable." },
      { title: "Escalate policy issues", body: "Ask an administrator for help with extension versions, school blocks, managed configuration, provider policy, setup keys, or official roster and schedule changes." },
    ],
    tips: ["Include the student’s displayed status, the action, and the approximate time when reporting a problem. Do not send passwords or sign-in URLs."],
  },
];
