import { useCallback, useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { myDeskApi } from '../lib/myDesk';
import { myDeskKeys, myDeskError } from '../lib/myDeskModel';
import { Button } from '../../../components/ui/button';
import { Input } from '../../../components/ui/input';
import { Textarea } from '../../../components/ui/textarea';
import { useMyDeskClasses, useMyDeskCategories, useMyDeskStudents } from '../hooks/useMyDesk';
import { formDraft, formPatch, reviewProblem } from '../lib/importReviewModel';
import { ImportConfirm, ImportImage } from './ImportShared';

export default function ImportForm({ access, batch, item, locked, run, onDirty, saveDraftRef, onNext }) {
  const discipline = batch.destination === 'discipline';
  const [draft, setDraft] = useState(() => ({ ...formDraft(item), ...(discipline ? { disciplineFields: item.disciplineFields || { referral: false, detentionAssignment: null }, duplicateDecision: item.duplicateDecision || null } : {}) })), [changed, setChanged] = useState(false), [error, setError] = useState(''), [confirm, setConfirm] = useState(null), [search, setSearch] = useState('');
  const [detentionDatesText, setDetentionDatesText] = useState(() => (item.disciplineFields?.detentionAssignment?.dates || []).join('\n'));
  const [zoom, setZoom] = useState(1), [readyPages, setReadyPages] = useState({});
  const [mobilePane, setMobilePane] = useState('preview');
  const previewReady = useCallback((id, ready) => setReadyPages(previous => previous[id] === ready ? previous : { ...previous, [id]: ready }), []);
  const allPreviewsReady = item.regions.length > 0 && item.regions.every(region => readyPages[region.assetId]);
  const classes = useMyDeskClasses(access.schoolId, access.viewerId), categories = useMyDeskCategories(access.schoolId, access.viewerId);
  const students = useMyDeskStudents(access.schoolId, access.viewerId, draft.groupId, { refetchOnMount: 'always', staleTime: 0 });
  const currentClasses = (classes.data?.current || []).filter(group => batch.selectedGroupIds?.includes(group.id));
  const roster = students.data?.students || [];
  const edit = (field, value) => { setDraft(previous => ({ ...previous, [field]: value, ...(field === 'groupId' ? { studentId: '' } : {}), ...(discipline && ['groupId','studentId','entryDate'].includes(field) ? { duplicateDecision: null } : {}) })); setChanged(true); onDirty(true); setError(''); };
  const duplicates = useQuery({ queryKey: [...myDeskKeys.root(access.schoolId, access.viewerId), 'import-duplicates', batch.id, item.id, draft.studentId, draft.entryDate],
    queryFn: ({ signal }) => myDeskApi(access.schoolId, signal).importDuplicates(batch.id, item.id, { studentId: draft.studentId, entryDate: draft.entryDate }),
    enabled: discipline && Boolean(draft.studentId && draft.entryDate) && !item.excluded, retry: false, gcTime: 0, staleTime: 0, refetchOnWindowFocus: 'always' });
  const otherForms = (batch.items || []).filter(form => !form.excluded && form.id !== item.id && form.studentId === draft.studentId && form.entryDate === draft.entryDate);
  const save = (reviewed = false, after) => {
    if (reviewed) {
      if (!allPreviewsReady) { setError('Wait for every form image to load before confirming review.'); return; }
      const problem = students.isError || students.isFetching ? 'Refresh and check the current student roster before reviewing.' : reviewProblem(item, draft, roster, students.data?.rosterRevision);
      if (problem) { setError(problem); return; }
      if (discipline && (!draft.body.trim() || (!draft.disciplineFields.referral && !draft.disciplineFields.detentionAssignment))) { setError('Confirm the factual summary and whether this is a referral or detention assignment.'); return; }
      if (discipline && (duplicates.isError || duplicates.isFetching || !duplicates.data || !draft.duplicateDecision || draft.duplicateDecision.candidatesFingerprint !== duplicates.data.candidatesFingerprint)) { setError('Check possible duplicates and choose how to save this form.'); return; }
      if (discipline && draft.duplicateDecision.action === 'add_evidence' && (!draft.duplicateDecision.recordId || !draft.duplicateDecision.reason?.trim())) { setError('Choose an existing incident and explain the added evidence.'); return; }
    }
    run('item', { itemRevision: item.revision, ...formPatch({ ...draft, ...(discipline && draft.duplicateDecision?.action === 'add_evidence' && (!draft.duplicateDecision.recordId || !draft.duplicateDecision.reason?.trim()) ? { duplicateDecision: null } : {}) }, students.data?.rosterRevision), reviewed }, item.id, after);
  };
  useEffect(() => { saveDraftRef.current = after => save(false, after); return () => { saveDraftRef.current = null; }; });
  const filtered = roster.filter(student => student.id === draft.studentId || (student.name || `${student.firstName} ${student.lastName}`).toLowerCase().includes(search.toLowerCase()));
  const warnings = item.warnings || [];
  return <section className="import-form-review" data-mobile-pane={mobilePane}><div className="import-mobile-pane-tabs" aria-label="Form review view"><Button variant={mobilePane === 'preview' ? 'default' : 'outline'} aria-pressed={mobilePane === 'preview'} onClick={() => setMobilePane('preview')}>Form image</Button><Button variant={mobilePane === 'fields' ? 'default' : 'outline'} aria-pressed={mobilePane === 'fields'} onClick={() => setMobilePane('fields')}>Student and details</Button></div><div className="import-form-image"><div className="import-crop-heading"><h2>Form {item.ordinal + 1}</h2><span>{item.excluded ? 'Excluded' : item.reviewed && !changed ? 'Reviewed' : 'Needs review'}</span></div><div className="import-actions import-preview-controls"><Button variant="outline" disabled={zoom >= 3} onClick={() => setZoom(value => value + .5)}>Zoom in form</Button><Button variant="ghost" disabled={zoom === 1} onClick={() => setZoom(1)}>Fit form</Button></div><div className="import-continuation-previews">{item.regions.map((region, index) => <figure key={`${region.assetId}:${index}`}><div className="import-preview-scroll"><div style={{ width: `${zoom * 100}%` }}><ImportImage onReady={previewReady} access={access} importId={batch.id} assetId={region.assetId} region={region} dimensions={batch.assets.find(asset => asset.id === region.assetId)} alt={`Form ${item.ordinal + 1}, part ${index + 1}`} /></div></div><figcaption>Part {index + 1} of {item.regions.length}</figcaption></figure>)}</div><p className="import-muted">Check the whole form image. Only this approved crop will be attached to the student’s {discipline ? 'disciplinary record' : 'note'}.</p>{item.extractionStatus === 'failed' && <p className="import-error">The form could not be read. Check its crop and try reading it again.</p>}<Button variant="outline" disabled={locked || changed || item.extractionStatus === 'pending' || item.excluded} onClick={() => setConfirm({ title: 'Re-read this form?', description: 'This reads the corrected form image again and replaces the draft title, body, category and date. Your edited text will be replaced. Check it again before saving.', label: 'Replace draft with new reading', action: () => run('reread', { itemRevision: item.revision }, item.id) })}>Re-read corrected form</Button><Button className="import-mobile-fields-action" onClick={() => setMobilePane('fields')}>Check student and details</Button></div>
    <div className="import-form-fields"><h3>Check the subject and details</h3><p>Check handwriting and names carefully. File this under the student the form is about, not a witness or reporter.</p>
      {!!item.subjectNames?.length && <div className="import-notice"><strong>Possible subject names from the form</strong><p>{item.subjectNames.map(name => typeof name === 'string' ? name : name.name || '').join(', ')}</p><small>These are suggestions. Select an exact student below.</small></div>}
      {!!warnings.length && <div className="import-warning" role="note"><strong>Check carefully</strong><ul>{warnings.map((warning, index) => <li key={index}>{typeof warning === 'string' ? warning : warning.message || warning.code}</li>)}</ul></div>}
      {item.excluded ? <div className="import-notice"><h3>This form is excluded.</h3><p>It will not be saved as a record.</p><Button disabled={locked || !item.regions.length} onClick={() => run('item', { itemRevision: item.revision, excluded: false, reviewed: false }, item.id)}>Include this form again</Button>{!item.regions.length && <p>Add a form region on the Pages step to include this paperwork.</p>}<Button variant="ghost" disabled={locked} onClick={onNext}>Next form</Button></div> : <>
      <fieldset disabled={locked}><div className="import-field-pair"><label>Subject’s class<select aria-label="Subject class" value={draft.groupId} onChange={event => edit('groupId', event.target.value)}><option value="">Choose a class</option>{currentClasses.map(group => <option key={group.id} value={group.id}>{group.name}</option>)}</select></label>{!discipline && <label>Category<select aria-label="Form category" value={draft.category} onChange={event => edit('category', event.target.value)}>{categories.data?.categories?.map(category => <option key={category.key} value={category.key}>{category.label}</option>)}</select></label>}</div>
      <label>Find the exact student<Input aria-label="Find subject student" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search this class" disabled={!draft.groupId} /></label><label>Subject student<select aria-label="Subject student" value={draft.studentId} disabled={!draft.groupId || students.isError || students.isPending} onChange={event => edit('studentId', event.target.value)}><option value="">Choose the subject student</option>{filtered.map(student => <option key={student.id} value={student.id}>{student.name || `${student.firstName} ${student.lastName}`}</option>)}</select></label>{students.isError && <p role="alert">The current roster could not be confirmed. <button type="button" onClick={() => students.refetch()}>Refresh roster</button></p>}
      <div className="import-date-field"><label>Form date<Input aria-label="Form date" type="date" value={draft.entryDate} onChange={event => edit('entryDate', event.target.value)} /></label>{access.schoolDate && <Button variant="outline" onClick={() => edit('entryDate', access.schoolDate)}>Use today</Button>}</div>{!draft.entryDate && <p className="import-muted">No date has been selected. Check the form before using today’s date.</p>}
      {discipline && <div className="import-notice"><h3>Incident information</h3><label><input type="checkbox" checked={draft.disciplineFields.referral} onChange={event => edit('disciplineFields', { ...draft.disciplineFields, referral: event.target.checked })} />Referral recorded</label><label><input type="checkbox" checked={!!draft.disciplineFields.detentionAssignment} onChange={event => { setDetentionDatesText(''); edit('disciplineFields', { ...draft.disciplineFields, detentionAssignment: event.target.checked ? { dates: [], details: '' } : null }); }} />Detention assigned</label>
      {draft.disciplineFields.detentionAssignment && <><label>Scheduled detention dates<textarea placeholder="YYYY-MM-DD, one date per line" value={detentionDatesText} onChange={event => { setDetentionDatesText(event.target.value); edit('disciplineFields', { ...draft.disciplineFields, detentionAssignment: { ...draft.disciplineFields.detentionAssignment, dates: event.target.value.split(/[\n,]/).map(value => value.trim()).filter(Boolean) } }); }} /></label><p>Several dates count as one assignment. Check the source; completion is not assumed.</p></>}
      <h3>Possible duplicates</h3>{duplicates.isFetching ? <p role="status">Checking existing incidents…</p> : duplicates.isError ? <p role="alert">{myDeskError(duplicates.error)} <button type="button" onClick={() => duplicates.refetch()}>Retry duplicate check</button></p> : duplicates.data && <>
      {!duplicates.data.candidates.length ? <p>No similar published incident was found.</p> : duplicates.data.candidates.map(candidate => <p key={candidate.id}><a href={`/classpilot/discipline-records/${candidate.id}`} target="_blank" rel="noreferrer">{candidate.entryDate} — {candidate.title || 'View existing incident'}</a></p>)}
      {!!otherForms.length && <p>There {otherForms.length === 1 ? 'is another form' : 'are other forms'} for this student and date in this packet. Separate incident will count this form separately. Join continuation forms on the Pages step when they describe one incident.</p>}
      <label>Save this form as<select value={draft.duplicateDecision?.action || ''} onChange={event => edit('duplicateDecision', event.target.value ? { action: event.target.value, candidatesFingerprint: duplicates.data.candidatesFingerprint } : null)}><option value="">Choose after checking</option><option value="separate">Separate incident</option>{duplicates.data.candidates.some(candidate => candidate.canAddEvidence) && <option value="add_evidence">Add evidence to existing incident</option>}</select></label>
      {draft.duplicateDecision?.action === 'add_evidence' && <><label>Existing incident<select value={draft.duplicateDecision.recordId || ''} onChange={event => { const candidate = duplicates.data.candidates.find(value => value.id === event.target.value); edit('duplicateDecision', { ...draft.duplicateDecision, recordId: candidate?.id, revision: candidate?.revision }); }}><option value="">Choose an incident you can correct</option>{duplicates.data.candidates.filter(candidate => candidate.canAddEvidence).map(candidate => <option key={candidate.id} value={candidate.id}>{candidate.entryDate} — {candidate.title || 'Incident'}</option>)}</select></label><label>Reason for adding evidence<textarea maxLength={2000} value={draft.duplicateDecision.reason || ''} onChange={event => edit('duplicateDecision', { ...draft.duplicateDecision, reason: event.target.value })} /></label><p>The existing incident and its counts stay unchanged.</p></>}
      <p>Use Exclude form below to exclude a duplicate.</p></>}
      </div>}
      <label>Title <small>(optional)</small><Input aria-label="Form title" value={draft.title} maxLength={160} onChange={event => edit('title', event.target.value)} /></label><label>{discipline ? 'Factual summary' : 'Note text'} <small>{discipline ? '(required)' : '(optional)'}</small><Textarea aria-label="Form note text" rows={8} value={draft.body} maxLength={5000} onChange={event => edit('body', event.target.value)} /></label>
      </fieldset>{error && <p role="alert" className="import-error">{error}</p>}
      <div className="import-review-attestation">Choosing Reviewed → Next confirms the subject student, class, date, text and complete form image.</div>
      <div className="import-actions"><Button disabled={locked || !allPreviewsReady || item.extractionStatus !== 'ready' || students.isFetching} onClick={() => save(true, onNext)}>Reviewed → Next</Button><Button variant="outline" disabled={locked || !changed} onClick={() => save()}>Save draft changes</Button><Button variant="ghost" disabled={locked} onClick={() => setConfirm({ title: 'Exclude this form?', description: 'This form will stay in the review as excluded and will not be saved. Unsaved text changes on this screen will be discarded.', label: 'Exclude form', action: () => run('item', { itemRevision: item.revision, excluded: true, reviewed: false }, item.id, onNext) })}>Exclude form</Button></div>
      </>}
    </div><ImportConfirm request={confirm} onClose={() => setConfirm(null)} />
  </section>;
}
