import { useEffect, useRef, useState } from 'react';
import { Button } from '../../../components/ui/button';
import { importPages, regionOnPage, regionFromPage, rotateRegion, clipRegion, IMPORT_LIMITS } from '../lib/importReviewModel';
import { ImportImage, ImportConfirm } from './ImportShared';

export default function ImportPages({ access, batch, locked, run, onDirty, saveDraftRef, onForms, selection, onSelection }) {
  const pages = importPages(batch); const [pageId, setPageId] = useState(selection.pageId || pages[0]?.id || '');
  const [itemId, setItemId] = useState(selection.itemId || ''), [regions, setRegions] = useState(null), [regionIndex, setRegionIndex] = useState(0), [history, setHistory] = useState([]), [confirm, setConfirm] = useState(null), [joiningId, setJoiningId] = useState('');
  const page = pages.find(item => item.id === pageId) || pages[0], selected = batch.items?.find(item => item.id === itemId);
  const draft = regions || selected?.regions || [], region = draft[regionIndex];
  const stage = useRef(null), drag = useRef(null);
  const dirty = regions !== null;
  const change = next => { setHistory(previous => [...previous.slice(-39), structuredClone(draft)]); setRegions(next); onDirty(true); };
  const select = (item, index) => { const action = () => { setItemId(item.id); onSelection({ pageId, itemId: item.id }); setRegions(null); setHistory([]); setRegionIndex(index); onDirty(false); }; if (dirty) setConfirm({ title: 'Discard crop changes?', description: 'Save these crop corrections first to keep them.', label: 'Discard changes', action }); else action(); };
  const save = after => { if (!selected || !dirty) return; run('item', { itemRevision: selected.revision, regions: draft, ...(draft.length ? {} : { excluded: true }) }, selected.id, after); };
  useEffect(() => { saveDraftRef.current = save; return () => { saveDraftRef.current = null; }; });
  const boxChange = (patch, remember = true) => {
    if (!region) return; const next = draft.map((value, index) => index === regionIndex ? regionFromPage(clipRegion({ ...regionOnPage(value), ...patch }), value.rotation, value.assetId) : value);
    if (remember) change(next); else { setRegions(next); onDirty(true); }
  };
  const pointerStart = (event, item, index, resize = false) => {
    if (locked || item.id !== itemId || !stage.current) return;
    event.preventDefault(); event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId);
    const bounds = stage.current.getBoundingClientRect(), current = draft[index]; if (!current) return;
    setRegionIndex(index); setHistory(previous => [...previous.slice(-39), structuredClone(draft)]);
    drag.current = { x: event.clientX, y: event.clientY, bounds, box: regionOnPage(current), index, resize, snapshot: structuredClone(draft) };
  };
  const pointerMove = event => {
    const value = drag.current; if (!value || locked) return;
    const dx = (event.clientX - value.x) / value.bounds.width, dy = (event.clientY - value.y) / value.bounds.height;
    const updated = value.resize ? { ...value.box, width: value.box.width + dx, height: value.box.height + dy } : { ...value.box, x: Math.max(0, Math.min(1 - value.box.width, value.box.x + dx)), y: Math.max(0, Math.min(1 - value.box.height, value.box.y + dy)) };
    setRegions(value.snapshot.map((valueRegion, index) => index === value.index ? regionFromPage(updated, valueRegion.rotation, valueRegion.assetId) : valueRegion)); onDirty(true);
  };
  const decision = batch.pageDecisions?.find(value => value.assetId === page?.id);
  const includedOnPage = batch.items?.filter(item => !item.excluded && item.regions.some(value => value.assetId === page?.id)) || [];
  const account = excluded => run('batch', { pageDecisions: [...(batch.pageDecisions || []).filter(value => value.assetId !== page.id), { assetId: page.id, excluded }] });
  const visibleItems = (batch.items || []).map(item => item.id === itemId && regions ? { ...item, regions } : item);
  const displayedBox = region ? regionOnPage(region) : null;
  return <section className="import-page-review"><div className="import-section-intro"><h2>Account for every form on every page</h2><p>Keep one numbered region per form. Add another region to the same form for a continuation. Check that no neighbouring student’s form is inside a crop.</p></div>
    <div className="import-page-thumbs" aria-label="Pages">{pages.map((asset, index) => <button key={asset.id} disabled={locked} aria-pressed={asset.id === page?.id} onClick={() => { setPageId(asset.id); onSelection({ pageId: asset.id, itemId }); }}><ImportImage access={access} importId={batch.id} assetId={asset.id} alt={`Page ${index + 1} thumbnail`} /><span>Page {index + 1}{batch.pageDecisions?.some(value => value.assetId === asset.id) ? ' ✓' : ''}</span></button>)}</div>
    {page ? <div className="import-crop-grid"><div><div className="import-crop-heading"><h3>Page {pages.findIndex(value => value.id === page.id) + 1}</h3><span>{decision ? decision.excluded ? 'Page excluded' : 'Accounted for' : 'Needs page check'}</span></div><div ref={stage} className="import-crop-stage"><ImportImage access={access} importId={batch.id} assetId={page.id} alt={`Original page ${pages.findIndex(value => value.id === page.id) + 1}`}>
      {visibleItems.flatMap(item => item.regions.map((value, index) => ({ item, value, index }))).filter(({ value }) => value.assetId === page.id).map(({ item, value, index }) => { const box = regionOnPage(value), active = item.id === itemId && index === regionIndex; return <div key={`${item.id}:${index}`} className={`import-region ${active ? 'is-selected' : ''} ${item.excluded ? 'is-excluded' : ''}`} style={{ left: `${box.x * 100}%`, top: `${box.y * 100}%`, width: `${box.width * 100}%`, height: `${box.height * 100}%` }} onPointerMove={pointerMove} onPointerUp={() => { drag.current = null; }} onPointerCancel={() => { drag.current = null; }}><button type="button" className="import-region-hit" disabled={locked} aria-label={`Select form ${item.ordinal + 1} region ${index + 1}`} onClick={() => { if (item.id !== itemId) select(item, index); else setRegionIndex(index); }} onPointerDown={event => pointerStart(event, item, index)} onKeyDown={event => { if (!active || !['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'].includes(event.key)) return; event.preventDefault(); const delta = .005; const dx = event.key === 'ArrowLeft' ? -delta : event.key === 'ArrowRight' ? delta : 0, dy = event.key === 'ArrowUp' ? -delta : event.key === 'ArrowDown' ? delta : 0; boxChange(event.shiftKey ? { width: box.width + dx, height: box.height + dy } : { x: Math.max(0, Math.min(1 - box.width, box.x + dx)), y: Math.max(0, Math.min(1 - box.height, box.y + dy)) }); }}><span>{item.ordinal + 1}{item.regions.length > 1 ? `.${index + 1}` : ''}{item.excluded ? ' · excluded' : ''}</span></button>{active && <button className="import-region-resize" aria-label="Drag to resize selected region" disabled={locked} onPointerDown={event => pointerStart(event, item, index, true)} />}</div>; })}
    </ImportImage></div><div className="import-actions"><Button disabled={locked || dirty || !includedOnPage.length} variant={decision && !decision.excluded ? 'outline' : 'default'} onClick={() => account(false)}>All forms on this page are accounted for</Button><Button variant="outline" disabled={locked || dirty || includedOnPage.length > 0} onClick={() => account(true)}>Exclude this whole page</Button></div><p className="import-muted">To exclude a whole page, first exclude its forms. Blank pages can be excluded directly.</p></div>
    <aside className="import-crop-inspector"><h3>Form regions</h3><label>Selected form<select aria-label="Select crop form" disabled={locked} value={selected?.id || ''} onChange={event => { const item = batch.items.find(value => value.id === event.target.value); if (item) select(item, 0); }}><option value="">Choose a form</option>{batch.items?.map(item => <option key={item.id} value={item.id}>Form {item.ordinal + 1}{item.excluded ? ' (excluded)' : ''}</option>)}</select></label>
      <Button variant="outline" disabled={locked || dirty || batch.items.length >= IMPORT_LIMITS.forms} onClick={() => run('add', { regions: [{ assetId: page.id, x: .1, y: .1, width: .8, height: .25, rotation: 0 }] })}>Add missed form on this page</Button>
      {selected && <><p className="import-muted">Form {selected.ordinal + 1} · {draft.length} {draft.length === 1 ? 'region' : 'regions'}</p><label>Region<select aria-label="Selected region" disabled={locked} value={regionIndex} onChange={event => { const index = Number(event.target.value); setRegionIndex(index); if (draft[index]) setPageId(draft[index].assetId); }}>{draft.map((value, index) => <option key={index} value={index}>{index + 1} · Page {pages.findIndex(asset => asset.id === value.assetId) + 1}</option>)}</select></label>
        {displayedBox && <><div className="import-region-fields">{[['x', 'Left'], ['y', 'Top'], ['width', 'Width'], ['height', 'Height']].map(([key, label]) => <label key={key}>{label} %<input aria-label={`${label} percent`} disabled={locked} type="number" min={key === 'width' || key === 'height' ? 1 : 0} max="100" step="0.5" value={Math.round(displayedBox[key] * 1000) / 10} onChange={event => boxChange({ [key]: Number(event.target.value) / 100 })} /></label>)}</div><p className="import-muted">Arrow keys move a selected region; Shift + arrows resize it. The fields above work with touch or keyboard.</p><div className="import-actions"><Button variant="outline" disabled={locked} onClick={() => change(draft.map((value, index) => index === regionIndex ? rotateRegion(value) : value))}>Rotate form 90°</Button><Button variant="ghost" disabled={locked} onClick={() => { change(draft.filter((_, index) => index !== regionIndex)); setRegionIndex(0); }}>Remove region</Button></div><p className="import-muted">Reading rotation: {region.rotation}°</p></>}
        <Button variant="outline" disabled={locked || selected.excluded || draft.length >= IMPORT_LIMITS.regions} onClick={() => { change([...draft, { assetId: page.id, x: .1, y: .1, width: .8, height: .25, rotation: 0 }]); setRegionIndex(draft.length); }}>Add continuation on this page</Button>
        <label>Join an already detected continuation<select aria-label="Continuation form" disabled={locked || dirty || selected.excluded} value={joiningId} onChange={event => setJoiningId(event.target.value)}><option value="">Choose another form</option>{batch.items.filter(item => item.id !== selected.id && !item.excluded && item.regions.length + draft.length <= IMPORT_LIMITS.regions).map(item => <option key={item.id} value={item.id}>Form {item.ordinal + 1}</option>)}</select></label><Button variant="outline" disabled={locked || dirty || !joiningId || selected.excluded} onClick={() => { const source = batch.items.find(item => item.id === joiningId); setConfirm({ title: `Join form ${source.ordinal + 1} to form ${selected.ordinal + 1}?`, description: 'The selected continuation regions are appended in order. Its separate form is excluded. This form keeps its edited text and must be checked again.', label: 'Join continuation', action: () => run('join', { itemRevision: selected.revision, sourceItemId: source.id, sourceItemRevision: source.revision }, selected.id) }); }}>Join continuation</Button>
        <div className="import-actions"><Button disabled={locked || !dirty} onClick={() => save()}>Save crop corrections</Button><Button variant="outline" disabled={locked || !history.length} onClick={() => { const next = history.at(-1); setHistory(previous => previous.slice(0, -1)); setRegions(next); onDirty(true); }}>Undo crop change</Button></div><p className="import-muted">Saving rebuilds the form image and clears review. Your edited fields stay unchanged. Re-read text explicitly from the Forms step.</p>
      </>}
    </aside></div> : <p role="status">Rendered pages are not ready yet.</p>}
    <div className="import-actions"><Button disabled={locked || dirty} onClick={onForms}>Continue to forms</Button></div><ImportConfirm request={confirm} onClose={() => setConfirm(null)} />
  </section>;
}
