import assert from 'node:assert/strict';
import test, { before, after } from 'node:test';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import { createServer } from 'vite';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
let vite, browser, base;
const entry = `import React,{useState}from'react';import{createRoot}from'react-dom/client';import{MemoryRouter}from'react-router-dom';import{QueryClientProvider}from'@tanstack/react-query';import{queryClient}from'/src/lib/queryClient.js';import{DisciplineLibrary,RecordLoader}from'/src/products/classpilot/pages/DisciplineRecords.jsx';import DisciplineSubmitButton,{SubmissionReview}from'/src/products/classpilot/components/DisciplineSubmitButton.jsx';import{DisciplineAccessEditor}from'/src/products/classpilot/components/DisciplineAccessPanel.jsx';import{disciplineKeys}from'/src/products/classpilot/lib/discipline.js';import{clearMyDeskQueries}from'/src/products/classpilot/lib/myDeskModel.js';import{useDisciplineCapabilities}from'/src/products/classpilot/hooks/useDiscipline.js';import'/src/index.css';const h=React.createElement;window.refreshDiscipline=()=>queryClient.invalidateQueries({queryKey:['mydesk-private']});function Harness(){const[viewerId,setViewer]=useState('teacher-a');const identity={schoolId:'school-a',viewerId,enabled:true,eligible:true};const capability=useDisciplineCapabilities(identity);const access={...identity,capabilities:capability.data||{canSubmit:false,canViewSchool:false,canManageAccess:false}};const mode=new URLSearchParams(location.search).get('mode');const C=mode==='library'?DisciplineLibrary:mode==='access'?DisciplineAccessEditor:mode==='limit'?SubmissionReview:mode==='record'?RecordLoader:DisciplineSubmitButton;return h(React.Fragment,null,h('button',{onClick:()=>{clearMyDeskQueries(queryClient);window.__viewer='teacher-b';setViewer('teacher-b')}},'Switch author'),h('div',{className:'mydesk-page discipline-page'},capability.usable?h(C,{key:viewerId,access,recordId:'record-a',noteIds:mode==='limit'?Array.from({length:51},(_,i)=>'note-'+i):['note-a','note-b'],onClose:()=>{window.__closed=true}}):h('p',null,'Access unavailable')));}createRoot(document.getElementById('root')).render(h(QueryClientProvider,{client:queryClient},h(MemoryRouter,null,h(Harness))));`;
before(async () => {
  vite=await createServer({root,logLevel:'error',cacheDir:`node_modules/.vite-discipline-${process.pid}`,server:{host:'127.0.0.1',port:0},plugins:[{name:'discipline-browser',configureServer(server){server.middlewares.use(async(req,res,next)=>{if(!req.url?.startsWith('/__discipline?'))return next();res.setHeader('Content-Type','text/html');res.end(await server.transformIndexHtml(req.url,'<!doctype html><html><meta name="viewport" content="width=device-width,initial-scale=1"><body><div id="root"></div><script type="module" src="/__discipline-entry.jsx"></script></body></html>'));});},resolveId(id){if(id==='/__discipline-entry.jsx')return '\0discipline-entry';},load(id){if(id==='\0discipline-entry')return entry;}}]});
  await vite.listen();base=`http://127.0.0.1:${vite.httpServer.address().port}`;browser=await chromium.launch({headless:true});
});
after(async()=>{await browser?.close();await vite?.close();});
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=','base64');
const version=(number,title=`Version ${number}`)=>({id:`version-${number}`,number,kind:number===1?'submission':'correction',studentId:'student-a',studentName:'Synthetic Student',classId:'class-a',className:'Grade five',category:'referral',entryDate:'2026-09-26',title,body:'Synthetic submitted summary.',reason:number===1?'':'Correction history',createdAt:'2026-09-26T12:00:00.000Z',attachments:[{id:`evidence-${number}`,filename:'synthetic.png',contentType:'image/png'}]});
const record=(revision=3)=>({id:'record-a',revision,status:'submitted',canCorrect:true,canWithdraw:true,currentVersion:version(revision),versions:[version(revision),version(revision-1)],nextVersionsCursor:revision-1,submittedBy:{id:'teacher-a',name:'Synthetic Teacher'}});
async function setup(mode, options = {}) {
  const page=await browser.newPage({viewport:{width:390,height:844}}),requests=[],errors=[];
  const state={capabilityStatus:200,recordStatus:200,blobStatus:200,submitFail:true,correctionMode:'conflict',correctionCalls:[],submissions:[],grants:[],failGrant:true,revision:3,withdrawals:[],withdrawConflict:false,withdrawn:false,canViewSchool:true,recordAuthor:'teacher-a',...options};
  page.on('pageerror',error=>errors.push(error.message));
  await page.addInitScript(()=>{window.__viewer='teacher-a';window.__revoked=[];localStorage.setItem('sp_activeSchoolId','school-a');const revoke=URL.revokeObjectURL.bind(URL);URL.revokeObjectURL=url=>{window.__revoked.push(url);revoke(url)};});
  await page.route('**/api/**',async route=>{
    const request=route.request(),url=new URL(request.url()),method=request.method(),body=method==='GET'?undefined:request.postDataJSON();requests.push({path:url.pathname,query:url.search,method,body});const json=(value,status=200)=>route.fulfill({json:value,status});
    if(url.pathname.endsWith('/csrf'))return json({csrfToken:'synthetic'});
    if(url.pathname.endsWith('/capabilities'))return state.capabilityStatus===200?json({canSubmit:true,canViewSchool:state.canViewSchool,canManageAccess:true}):json({error:'Capability temporarily unavailable'},state.capabilityStatus);
    if(url.pathname.includes('/content'))return state.blobStatus===200?route.fulfill({contentType:'image/png',body:png}):json({error:'Access revoked'},state.blobStatus);
    if(url.pathname.includes('/mydesk/notes/')){const id=url.pathname.split('/').at(-1);return json({note:{id,targetKind:'student',status:'active',revision:2,studentName:id==='note-a'?'First Synthetic':'Second Synthetic',groupName:'Grade five',title:'Private source',body:'Only explicitly selected material is shared.',category:'referral',entryDate:'2026-09-26',attachments:[{id:`${id}-file`,status:'ready',committedAt:'2026-09-26T00:00:00Z',originalFilename:'synthetic.png',contentType:'image/png'}]}});}
    if(url.pathname.endsWith('/students/student-a/history'))return json({student:{id:'student-a',name:'Synthetic Student',current:false},notes:[{id:'historical-note',targetKind:'student',status:'active',revision:2,entryDate:'2025-01-01',title:'Preserved past-class evidence',attachments:[]}],nextCursor:null});
    if(url.pathname.endsWith('/submit')){state.submissions.push(body);if(body.noteId==='note-b'&&state.submitFail){state.submitFail=false;return json({error:'Synthetic interrupted response'},503);}return json({record:{id:`record-${body.noteId}`}});}
    if(url.pathname.endsWith('/correct')){state.correctionCalls.push(body);if(state.correctionMode==='conflict'){state.revision=4;state.correctionMode='success';return json({error:'This record changed',code:'DISCIPLINE_REVISION_CONFLICT'},409);}return json({record:record(5)});}
    if(url.pathname.endsWith('/withdraw')){state.withdrawals.push(body);if(state.withdrawConflict){state.withdrawConflict=false;state.revision++;return json({error:'This record changed',code:'DISCIPLINE_REVISION_CONFLICT'},409);}state.withdrawn=true;return json({record:{...record(),status:'withdrawn'}});}
    if(url.pathname.endsWith('/access/teacher-a')){state.grants.push(body);if(state.failGrant){state.failGrant=false;return json({error:'Temporary permission interruption'},503);}return json({ok:true});}
    if(url.pathname.endsWith('/access'))return json({staff:[{userId:'teacher-a',name:'Synthetic Teacher',email:'synthetic@example.test',enabled:false,revision:0}]});
    if(url.pathname.endsWith('/search'))return json({records:body.scope==='own'?[]:[record()],nextCursor:null});
    if(url.pathname.endsWith('/export'))return route.fulfill({contentType:'text/csv',body:'student\nSynthetic Student'});
    if(url.pathname.endsWith('/record-a')){if(state.recordStatus!==200)return json({error:'Record temporarily unavailable'},state.recordStatus);if(url.searchParams.has('versionsCursor'))return json({record:{...record(state.revision),versions:[version(1,'Earliest submission')],nextVersionsCursor:null}});return json({record:{...record(state.revision),submittedBy:{id:state.recordAuthor,name:'Synthetic Teacher'},...(state.withdrawn?{status:'withdrawn',canWithdraw:false}:{})}});}
    return json({error:'Unexpected synthetic endpoint'},404);
  });
  await page.goto(`${base}/__discipline?mode=${mode}`);return{page,requests,errors,state};
}
const noOverflow=async page=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);

test('explicit school submission shares only selected forms and retries unfinished entries with stable keys',async()=>{
  const {page,state,errors}=await setup('submit');try{
    await page.getByRole('button',{name:'Submit to school log',exact:true}).click();await page.getByRole('heading',{name:'Review school log submission'}).waitFor();
    assert.equal(await page.getByRole('button',{name:'Submit 2 entries to school log'}).isDisabled(),true);
    await page.getByLabel('Include synthetic.png').first().uncheck();await page.getByLabel('I reviewed the selected entries and forms for submission.').check();
    await page.getByRole('button',{name:'Submit 2 entries to school log'}).click();await page.getByText(/Synthetic interrupted response/).waitFor();
    assert.equal(state.submissions[0].attachmentIds.length,0);assert.equal(state.submissions[1].attachmentIds.length,1);
    await page.getByRole('button',{name:'Retry 1 remaining'}).click();await page.getByText('2 school records submitted. Your private notes are unchanged.').waitFor();
    assert.deepEqual(state.submissions[1],state.submissions[2]);assert.equal(state.submissions.filter(row=>row.noteId==='note-a').length,1);await noOverflow(page);assert.deepEqual(errors,[]);
  }finally{await page.close();}
});
test('capability refresh503 preserves reviewed selections,403 removes private review, and more than50 is never truncated',async()=>{
  const {page,state,errors}=await setup('submit');try{await page.getByRole('button',{name:'Submit to school log',exact:true}).click();await page.getByLabel('I reviewed the selected entries and forms for submission.').check();state.capabilityStatus=503;await page.evaluate(()=>window.refreshDiscipline());assert.equal(await page.getByLabel('I reviewed the selected entries and forms for submission.').isChecked(),true);state.capabilityStatus=403;await page.evaluate(()=>window.refreshDiscipline());await page.getByRole('heading',{name:'Review school log submission'}).waitFor({state:'hidden'});assert.deepEqual(errors,[]);}finally{await page.close();}
  const limited=await setup('limit');try{await limited.page.getByText(/None of these 51 notes were submitted/).waitFor();assert.equal(limited.requests.filter(row=>row.path.includes('/mydesk/notes/')).length,0);assert.equal(limited.state.submissions.length,0);}finally{await limited.page.close();}
});
test('school library uses private filtered POST search/export and accurate active-and-withdrawn label',async()=>{
  const {page,requests,errors}=await setup('library');try{await page.getByRole('heading',{name:'Discipline records'}).waitFor();await page.getByLabel('Status',{exact:true}).selectOption('all');await page.getByLabel('Student name').fill('Synthetic');await page.getByLabel('Search records').fill('private filter');await page.waitForTimeout(200);await page.getByRole('button',{name:'Export filtered CSV'}).click();await page.waitForTimeout(150);const exported=requests.find(row=>row.path.endsWith('/export'));assert.equal(exported.body.status,'all');assert.equal(exported.body.q,'private filter');assert.equal(exported.body.studentName,'Synthetic');assert.equal(exported.query,'');assert.equal(await page.getByRole('option',{name:'Active and withdrawn'}).count(),1);await noOverflow(page);await page.screenshot({path:path.join(os.tmpdir(),'schoolpilot-discipline-library-phone.png'),fullPage:true});assert.deepEqual(errors,[]);}finally{await page.close();}
});
test('correction conflict retains draft, requires latest-version review, and hides unsaved text when printing',async()=>{
  const {page,state,errors}=await setup('record');try{await page.getByRole('button',{name:'Correct submission',exact:true}).click();await page.waitForTimeout(100);assert.deepEqual(errors,[]);await page.getByLabel('Title',{exact:true}).fill('Unsaved private correction');await page.getByLabel('Reason for correction').fill('Synthetic reason');await page.getByLabel('I reviewed the corrected entry and selected forms.').check();await page.getByRole('button',{name:'Submit correction',exact:true}).click();await page.getByRole('button',{name:'Review latest saved version'}).click();await page.getByRole('heading',{name:'Latest saved submission'}).waitFor();assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'Unsaved private correction');await page.getByRole('button',{name:'Keep my draft against this version'}).click();assert.equal(await page.getByLabel('I reviewed the corrected entry and selected forms.').isChecked(),false);
    state.recordStatus=503;await page.evaluate(()=>window.refreshDiscipline());assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'Unsaved private correction');state.recordStatus=200;
    await page.screenshot({path:path.join(os.tmpdir(),'schoolpilot-discipline-correction-phone.png'),fullPage:true});await page.emulateMedia({media:'print'});assert.equal(await page.getByRole('dialog').isVisible(),false);assert.equal(await page.locator('body > .fixed.inset-0[data-state=open]').isVisible(),false);await page.screenshot({path:path.join(os.tmpdir(),'schoolpilot-discipline-print.png'),fullPage:true});await page.emulateMedia({media:'screen'});
    await page.getByLabel('I reviewed the corrected entry and selected forms.').check();await page.getByRole('button',{name:'Submit correction',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(state.correctionCalls[1].revision,4);assert.equal(state.correctionCalls[1].title,'Unsaved private correction');assert.deepEqual(state.correctionCalls[1].attachmentIds,[]);assert.deepEqual(errors,[]);
  }finally{await page.close();}
});
test('history loads older version pages; revoked attachment URLs and switched owner content clear',async()=>{
  const {page,state,requests,errors}=await setup('record');try{await page.getByRole('button',{name:'Show version history'}).click();await page.getByRole('button',{name:'Older versions'}).click();await page.getByRole('heading',{name:'Earliest submission'}).waitFor();assert.ok(requests.some(row=>row.query==='?versionsCursor=2'));await page.getByRole('button',{name:'View submitted forms (1)'}).first().click();await page.getByRole('img',{name:'synthetic.png'}).waitFor();state.blobStatus=403;await page.evaluate(()=>window.refreshDiscipline());await page.getByRole('img',{name:'synthetic.png'}).waitFor({state:'hidden'});assert.ok(await page.evaluate(()=>window.__revoked.length>0));state.recordStatus=403;await page.getByRole('button',{name:'Switch author'}).click();await page.getByRole('heading',{name:'Record unavailable'}).waitFor();assert.equal(await page.getByText('Synthetic submitted summary.').count(),0);assert.deepEqual(errors,[]);}finally{await page.close();}
});
test('school viewing permission requires confirmation and reuses uncertain change key',async()=>{
  const {page,state,errors}=await setup('access');try{await page.getByRole('button',{name:'Grant access'}).click();await page.getByRole('region',{name:'Confirm discipline permission'}).waitFor();assert.equal(state.grants.length,0);await page.getByRole('button',{name:'Confirm permission change'}).click();await page.getByText('Temporary permission interruption').waitFor();await page.getByRole('button',{name:'Retry permission change'}).click();await page.getByText('Discipline viewing access granted.').waitFor();assert.deepEqual(state.grants[0],state.grants[1]);assert.equal(state.grants[0].enabled,true);await noOverflow(page);assert.deepEqual(errors,[]);}finally{await page.close();}
});


test('withdrawal conflict preserves reason and requires refreshed record before retry',async()=>{
  const {page,state,errors}=await setup('record');try{state.withdrawConflict=true;await page.getByRole('button',{name:'Withdraw submission',exact:true}).click();await page.getByLabel('Withdrawal reason',{exact:true}).fill('Synthetic withdrawal reason');await page.getByRole('button',{name:'Confirm withdrawal'}).click();await page.getByRole('button',{name:'Review latest before withdrawal'}).waitFor();assert.equal(await page.getByRole('button',{name:'Confirm withdrawal'}).isDisabled(),true);await page.getByRole('button',{name:'Review latest before withdrawal'}).click();await page.getByText('Review the latest saved entry above before confirming withdrawal. Your reason is preserved.').waitFor();assert.equal(await page.getByLabel('Withdrawal reason',{exact:true}).inputValue(),'Synthetic withdrawal reason');await page.getByRole('button',{name:'Confirm withdrawal'}).click();await page.getByText('This submission was withdrawn and is retained as history. It is not an active incident record.').waitFor();assert.equal(state.withdrawals[1].revision,4);assert.equal(state.withdrawals[1].reason,'Synthetic withdrawal reason');assert.deepEqual(errors,[]);}finally{await page.close();}
});


test('successful school-view grant removal immediately drops cached school lists and other-author details',async()=>{
  const library=await setup('library');try{await library.page.getByRole('heading',{name:'Version 3'}).waitFor();library.state.canViewSchool=false;await library.page.evaluate(()=>window.refreshDiscipline());await library.page.getByRole('heading',{name:'No matching submissions'}).waitFor();assert.equal(await library.page.getByLabel('Records',{exact:true}).inputValue(),'own');assert.equal(await library.page.getByText('Synthetic Student',{exact:true}).count(),0);assert.equal(library.requests.filter(row=>row.path.endsWith('/search')).at(-1).body.scope,'own');}finally{await library.page.close();}
  const detail=await setup('record',{recordAuthor:'another-author'});try{await detail.page.getByRole('heading',{name:'Synthetic Student'}).waitFor();detail.state.canViewSchool=false;await detail.page.evaluate(()=>window.refreshDiscipline());await detail.page.getByText('Your school viewing permission is no longer active.').waitFor();assert.equal(await detail.page.getByText('Synthetic submitted summary.').count(),0);}finally{await detail.page.close();}
});

test('correcting past-class evidence uses only private student history with its exact class filter',async()=>{
  const {page,requests,errors}=await setup('record');try{await page.getByRole('button',{name:'Correct submission',exact:true}).click();await page.getByLabel('Replace forms with attachments from a private note').check();await page.getByRole('option',{name:'2025-01-01 — Preserved past-class evidence'}).waitFor({state:'attached'});const history=requests.find(row=>row.path.endsWith('/students/student-a/history'));assert.equal(history.method,'POST');assert.equal(history.query,'');assert.equal(history.body.classId,'class-a');assert.equal(requests.filter(row=>row.path.endsWith('/notes/search')).length,0);assert.deepEqual(errors,[]);}finally{await page.close();}
});
