import { createRoot } from "react-dom/client";
import { QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter } from "react-router-dom";
import { queryClient } from "../src/lib/queryClient";
import { ThemeProvider } from "../src/contexts/ThemeContext";
import SafetyCenter from "../src/products/classpilot/pages/SafetyCenter";
import MonitoringHoursSettings from "../src/products/classpilot/components/MonitoringHoursSettings";
import { schoolSettingsFixture } from "./school-settings-fixture.mjs";
import "../src/index.css";
const schoolSettings = schoolSettingsFixture();
const queryKey = ["/classpilot/admin/settings", schoolSettings.schoolId, "admin-a"];
schoolSettings.schoolTimezone = "America/Chicago";
schoolSettings.sections.monitoring.version = "a".repeat(64);
queryClient.setQueryData(queryKey, schoolSettings);
createRoot(document.getElementById("root")).render(<QueryClientProvider client={queryClient}><ThemeProvider><BrowserRouter><SafetyCenter /><MonitoringHoursSettings schoolId={schoolSettings.schoolId} queryKey={queryKey} settings={{ ...schoolSettings.sections.monitoring, schoolTimezone: schoolSettings.schoolTimezone }} /></BrowserRouter></ThemeProvider></QueryClientProvider>);
